export interface BlueprintBlock {
  title: string;
  body: string[];
  bullets?: string[];
  code?: string;
  table?: { headers: string[]; rows: string[][] };
}
export interface BlueprintSection {
  id: string; number: string; shortTitle: string; title: string; summary: string; tags: string[]; blocks: BlueprintBlock[];
}

export const blueprint: BlueprintSection[] = [
  {
    id: "architecture", number: "01", shortTitle: "Core architecture", title: "Verify the author. Not the algorithm.",
    summary: "An institution-owned evidence plane, a minimal public trust plane, and a student-controlled decision to participate.",
    tags: ["TanStack Start", "Bun + React 19", "Institution-local"],
    blocks: [
      { title: "The thesis and the consent boundary", body: [
        "AuthWords asks whether a particular submission is consistent with a particular student's authenticated writing history, under the assignment's permitted-assistance policy. It is not an AI detector, a plagiarism detector, or a measure of moral intent. A low score means insufficient support for verification—not evidence of misconduct. The ordinary academic grade is never reduced by declining verification.",
        "The data advantage is longitudinal and multimodal, not covert. Before any historical collection, the student sees the sources, time range, purpose, retention period, and recipients. Discussion posts, supervised timed writing, attributable group contributions, drafts, and peer feedback are separate consent scopes. Email is off by default: explicitly select authorized academic messages and remove other people's quoted content, signatures, and identifiers locally. Do not crawl an inbox or silently repurpose private communication.",
        "Offer a no-cost supervised writing or oral-defense pathway so that privacy-conscious students, students with sparse digital histories, and students with disabilities can earn the same enhancement. A Verified A preserves the instructor's A and adds evidence of authorship; it is not a higher numeric grade or a promise of employment. Measure whether the opt-in scheme creates coercion or unequal opportunity before expanding it.",
      ] },
      { title: "Two trust planes, one hard egress boundary", body: [
        "Deploy the evidence plane in a university-controlled Kubernetes cluster or an institution-owned private VPC with a contractually approved region. Source connectors, identity mapping, queues, feature extraction, inference, and the private student interface all remain inside that perimeter. AuthWords operators get no standing access. Each institution has separate databases, service accounts, encryption keys, and network policy; do not share a multi-tenant vector index.",
        "The public plane serves static product assets, federation public keys, revocation artifacts, and explicitly shared credential proofs. The model-result egress allowlist is only a rounded P(authorship | evidence), its uncertainty/abstention state, and a small controlled vocabulary of interpretative flags. Never export embeddings, source excerpts, per-feature fingerprints, course IDs, LMS user IDs, or a stable student identifier. Scores are still sensitive and are private by default; a public share requires separate authorization.",
      ], code: "UNIVERSITY TRUST BOUNDARY\nCanvas / Blackboard / Moodle / authorized mail\n    ↓ signed event or scoped reconciliation\nBun connector → PostgreSQL inbox + transactional outbox\n    ↓ opaque artifact reference, never text\nRedis 7 + BullMQ → Node 22 orchestration worker\n    ↓ institution-local fetch, consent re-check\nSECURE ANALYSIS BOX: local Python + ONNX → Bayesian ensemble\n    ↓ encrypted derived state; raw buffers discarded\nPrivate review UI → policy gate → institutional credential signer\n══════════════ EXPLICIT EGRESS ALLOWLIST ══════════════\nMinimal signed assertion → public verification + status list" },
      { title: "Native integration with the existing frontend", body: [
        "Keep the current TanStack Start application: React 19, Vite, @tailwindcss/vite for Tailwind CSS v4, @tanstack/react-router, and @tanstack/react-query. Use createServerFn for typed, schema-validated internal commands and server routes for OIDC/LTI form POSTs and machine webhooks. Zod validates every boundary. Drizzle with node-postgres connects to local PostgreSQL; jose handles JOSE messages. Server secrets must never use a VITE_ prefix.",
        "Build with bun --bun vite build and the documented nitro/vite plugin using the bun preset; run the emitted Bun server inside the institution. Pin the tested Bun, Start, React, Vite, and Nitro versions in bun.lock, build reproducibly with bun install --frozen-lockfile, and run Bun integration tests for session cookies, streaming, and LTI form posts. Nitro's integration evolves: upgrade behind a compatibility suite, not a floating latest deployment.",
        "Bun serves the web/BFF and lightweight connectors. BullMQ runs on a separately pinned Node 22 worker rather than assuming complete Bun compatibility with all Redis/Lua worker behavior. Python 3.12 workers host spaCy, scikit-learn, LightGBM, PyMC, and ONNX Runtime. The language boundary is protobuf over a Unix socket or mutually authenticated in-cluster gRPC. No remote model API is called. These are internal services, not a rewrite of the frontend.",
        "Reference-app boundary: this interactive workspace runs on the provided Next.js App Router / PostgreSQL sandbox. Its synthetic metrics, consent CRUD, and Ed25519 demo signatures are working features. The production target remains TanStack Start; LTI connections, the trained ensemble, confidential compute, and university identity are architectural specifications, not integrations secretly running in this demo.",
      ] },
      { title: "Queue semantics, scale, and observability", body: [
        "Normalize events to tenant, deployment, source, opaque subject, artifact, version, event time, received time, provenance class, consent receipt, and assignment-policy version. Deduplicate on (tenant, source, artifact, version). Atomically commit the inbox receipt and outbox record before acknowledging a webhook. The outbox relay can publish twice; workers use the same unique job key and idempotent result upserts. Claim at-least-once delivery, not impossible end-to-end exactly-once execution.",
        "Queue payloads contain only opaque institutional references. Fetch source text just in time after a second consent check. For sources with unavoidable text-bearing events, terminate inside the box, do not persist the body, and fetch authoritative content through the source API. If that is impossible, reject the integration until an institution-approved ephemeral path exists. Redis persistence and dead-letter queues never contain text.",
      ], bullets: [
        "Initial topology: 3 Bun replicas, 2 outbox relays using FOR UPDATE SKIP LOCKED, 2 Node orchestrators, 4 CPU inference workers; PostgreSQL primary plus synchronous standby and an institution-local Redis HA deployment. GPU inference is optional, not required for launch.",
        "Partition concurrency by institution and source, cap per-student work, honor Retry-After, and use exponential backoff with jitter. After five retryable failures, send only an opaque reference plus error code to the dead-letter queue. Malformed or revoked-consent jobs are not retried.",
        "Illustrative sizing, not a benchmark: 100,000 artifacts/day is 1.16 jobs/s average. A 20× peak is about 23 jobs/s. At a measured two seconds per job, provision at least 66 concurrent slots for 70% utilization, or equivalent tested batching. The initial four workers are a pilot, not the peak-capacity claim.",
        "Set targets of webhook acknowledgement p95 <250 ms and completed verification p95 <60 s for an ordinary 2,000-word artifact at rated load. Establish actual capacity with k6 and a synthetic corpus before committing an SLA.",
        "Use OpenTelemetry + Prometheus/Grafana locally with content-free spans. Measure queue age, abstention, calibration error, source lag, purge failures, and subgroup error intervals. Alert on content-shaped payloads and denied egress. No third-party session replay or model telemetry.",
      ] },
    ],
  },
  {
    id: "engine", number: "02", shortTitle: "Multi-factor engine", title: "Four signals. One contextual judgment.",
    summary: "A calibrated author-verification ensemble that models language, genre, provenance, and growth—not just similarity.",
    tags: ["spaCy + ONNX", "Bayesian state space", "Calibrated abstention"],
    blocks: [
      { title: "Input integrity before inference", body: [
        "Treat every submission as untrusted data, never instructions for an LLM. Validate encoding, MIME type, decompression bounds, and maximum length; use a sandboxed document parser with no macros or network. Canonicalize Unicode while retaining a separate local punctuation representation. Strip source markup, instructor prompts, quotations, bibliographies, and template text before measuring style. Record the excluded fraction and abstain when too little original material remains.",
        "Build baseline provenance from authenticated, attributable work. Weight supervised timed writing most strongly, then signed revision history and instructor-confirmed samples. Do not promote an unverified submission into the baseline merely because the model accepted it. Limit per-source and per-time-window influence; quarantine distribution shifts to resist gradual baseline poisoning. Reusing a shared account and highly skilled imitation remain residual threats requiring supervised evidence.",
      ] },
      { title: "The four input vectors", body: [], table: { headers: ["Vector", "Concrete extraction", "What it contributes"], rows: [
        ["Stylometry · xₛ", "Local spaCy dependency trees; POS and dependency-relation histograms; function-word rates; character 3–5 grams and word 1–2 grams via a keyed feature hasher; mean/variance of sentence length, burstiness, punctuation, and syntactic depth.", "Genre-conditioned author style. Normalize for text length with shrinkage and bootstrap uncertainty. Drop rare n-grams and raw lexical keys. A hash is not an anonymization guarantee."],
        ["Semantics · xₑ", "Sentence Transformers all-MiniLM-L6-v2, 384 dimensions, in local ONNX Runtime; for supported multilingual cohorts use a separately validated paraphrase-multilingual-MiniLM-L12-v2 model. Chunk, mean-pool, and compare conceptual transitions.", "Topic and conceptual progression as nuisance/context signals—not proof of authorship. Down-weight assignment overlap. Never use an external BERT/GPT API. Discard sentence embeddings after local distance computation."],
        ["Linguistic context · xₗ", "Voluntary language-learning history, course level, supported writing accommodations, and optional self-reported proficiency; partial-pooling growth curves in a PyMC hierarchical model.", "Adapt expected variability without inferring race, nationality, or ethnicity. Missing information is marginalized, never treated as suspicious. Cohort labels cannot directly increase a misconduct prior."],
        ["Temporal state · xₜ", "A multivariate local-linear state-space model over dated, provenance-weighted samples; Kalman filtering for continuous features and robust Student-t innovations, with term/genre effects.", "Separate gradual development from abrupt residual shifts over 4+ years. Long gaps widen intervals. Preserve semester-level sufficient statistics and bounded anchors, subject to retention authorization."],
      ] } },
      { title: "Temporal evolution is expected, not penalized", body: [
        "Let θₛ,t be the student's latent style/proficiency and vₛ,t its growth velocity. Infer both from historical trusted evidence, with observation covariance scaled by source reliability and sample length. The forecast distribution—not a frozen first-year fingerprint—is the baseline for a new sample. Change-point detection raises a request for context; a new genre, tutoring, a language course, or assistive technology can legitimately explain the change.",
      ], code: "θₛ,t = θₛ,t−1 + Δt · vₛ,t−1 + ηₜ\nvₛ,t = vₛ,t−1 + ζₜ\nxₛ,t = θₛ,t + B·genreₜ + C·permitted_toolsₜ + εₜ\nεₜ ~ Student-t(ν, 0, R / provenance_weight)\n\nObserve → forecast → compare residual → update only trusted anchors\nDo not train on the submission being verified." },
      { title: "Ensemble classifiers and the Bayesian network", body: [
        "Train an elastic-net logistic model on standardized stylometric distances and a LightGBM classifier on nonlinear interactions, provenance, length, and temporal residuals. A regularized Siamese contrastive encoder is a later option only after enough same-author/different-author pairs exist; it is not a cold-start dependency. Fit author-disjoint, assignment-disjoint, chronological out-of-fold predictions into a regularized logistic stacker, then calibrate on a separate institutional holdout with isotonic regression or temperature scaling.",
        "Use Ledoit–Wolf shrinkage Mahalanobis distance and scikit-learn IsolationForest on provenance-filtered residuals for anomaly evidence; use Bayesian online change-point detection for sudden transitions. These generate interpretable context flags. An IsolationForest score is not P(authorship), and anomalies cannot trigger punishment or mint a negative credential.",
        "The Bayesian network contains H (same authorized author), θ (evolving latent style), G (genre), L (language-learning context), R (provenance reliability), A (permitted assistance), and correlated evidence Z from the stacker. Marginalize uncertainty over θ and unknown context. Do not multiply four independent posteriors: stylometry, semantics, and temporal residuals are dependent. Use a learned joint likelihood / interaction-aware fusion, with hierarchical priors partially pooled by institution and assignment type.",
        "Define the alternative hypothesis explicitly: another consenting author under matched genre, prompt, and length conditions—not a conveniently unrelated essay. Estimate the operational base rate from a justified deployment study, perform prior-sensitivity analysis, and publish the assumption in the private report. Without a representative alternative distribution and calibration study, label the output a consistency score and abstain from claiming a true posterior.",
      ], code: "Posterior odds(H | Z, C)\n  = prior odds(H | C) × p(Z | H=1, C) / p(Z | H=0, C)\n\nC = {genre, allowed assistance, source reliability, time, language context}\nP(H=1 | E) = ∫ P(H=1 | Z, θ, C, ω) p(θ, ω | trusted history) dθ dω\n\nPrivate result = { probability | null, uncertainty, decision, flag_codes,\n                   model_version, policy_version, baseline_version }" },
      { title: "Calibration, equity, and assignment-aware abstention", body: [
        "A pilot gate might require eight authenticated samples across two contexts, at least 1,500 baseline words, and at least 150 usable candidate words. These are starting hypotheses to validate—not universal scientific thresholds. Use subject-level bootstrap intervals, Brier score, log loss, ECE, reliability diagrams, and positive predictive value under prior shifts. Keep open-set authors and future semesters out of training; evaluate adversarial imitation, shared prompts, translated writing, and edited AI output separately.",
        "Select a positive-verification threshold using a preregistered false-verification budget, and report false-nonverification and abstention rates across adequately sized, consented linguistic cohorts with confidence intervals. Small cohorts require wider uncertainty or no deployment, not a silent default. Distribution-free conformal prediction can help construct an abstention set under exchangeability, but do not claim that its coverage survives arbitrary temporal or demographic drift.",
        "For prompt-engineering assignments, verify the student's prompts, iterative revisions, critique, source evaluation, and rationale—not the generated essay. The LMS supplies an explicit artifact role and permitted-tool policy. Route prompts to a prompt-specific baseline; missing provenance or a short prompt sequence yields insufficient evidence. Do not score generated output against an essay-writing profile. For collaborative work, verify only attributable contributions and clearly scope the credential.",
      ], bullets: [
        "Allowed output flags: SHORT_SAMPLE, SPARSE_BASELINE, GENRE_SHIFT, TEMPORAL_SHIFT, LANGUAGE_CONTEXT_NEEDED, PROVENANCE_GAP, and PROMPT_BASELINE_REQUIRED. No trait-based accusation or raw excerpt leaves the box.",
        "Decision states: Verified, Needs context, or Insufficient evidence. Student and instructor can provide additional supervised evidence, challenge the context, and obtain a human review. Never feed an unreviewed flag into a disciplinary system.",
        "Release model updates in shadow mode, compare calibration and subgroup behavior, sign model artifacts, record model/policy lineage, and retain an institution-approved rollback bundle. A model update must not silently rewrite issued credentials.",
      ] },
    ],
  },
  {
    id: "privacy", number: "03", shortTitle: "FERPA & data isolation", title: "The text stays. The evidence travels.",
    summary: "A local-processing privacy shield with enforceable boundaries, realistic erasure guarantees, and no magical anonymity claims.",
    tags: ["PostgreSQL + RLS", "Local keys", "No raw-text retention"],
    blocks: [
      { title: "The non-negotiable correction: vectors are not anonymous", body: [
        "Dense embeddings can leak or reconstruct text; published embedding-inversion attacks recover sensitive details. Hashing, a random projection, quantization, or deleting the original does not prove that a linguistic fingerprint is non-reversible. Even a coarse fingerprint can identify a person across records. AuthWords must treat all student-linked derived features as protected personal/education data and keep them inside the university. Promise bounded retention and minimized disclosure—not mathematically impossible absolute non-reversibility.",
        "Choose the localized-processing branch of the Secure Analysis Box. A container or confidential VM is not a zero-knowledge proof. A genuine ZK proof would require a defined statement and circuit, could prove execution of a committed computation, and would still not establish that the original author was the student. It is not a prerequisite for the launch architecture. Optional confidential-compute attestation strengthens isolation but does not replace access control, a DPIA, or verification of the model.",
        "FERPA does not categorically prohibit all third-party processing; authorized disclosures have conditions. GDPR and FERPA compliance cannot be certified by a diagram. Here the product deliberately adopts the stricter no-raw-egress rule. University counsel must document the applicable FERPA permission/exception, GDPR lawful basis, consent validity, processor agreements, data-subject rights, local retention schedule, and international-transfer constraints. No solely automated adverse academic decision is permitted.",
      ] },
      { title: "Institution-local relational schema", body: [
        "Use PostgreSQL 17 with explicit institution and pseudonymous-subject keys, composite foreign keys, transaction-local tenant context, and FORCE ROW LEVEL SECURITY. The web role cannot BYPASSRLS or own the tables. Bind tenant context from the verified session, not from request parameters, and test pool reuse so it cannot leak across transactions. Identity resolution is a separate database/service accessible only to the university's identity broker.",
      ], table: { headers: ["Table", "Important columns / constraints", "Retention & access"], rows: [
        ["identity_vault", "tenant_id, HMAC_subject_id, encrypted_LMS_subject; separate key and service", "Only the institution resolves a student. A keyed HMAC is pseudonymization, not anonymization."],
        ["consent_receipt", "tenant_id, subject_id, purpose, source_scope, policy_version, grant_at, withdraw_at", "Append-only minimal receipt with a published legal retention basis; no text."],
        ["artifact_receipt / outbox", "source_id, artifact_id, revision, opaque_subject_id, provenance, observed_at; unique event key", "No content, tokens, filenames, URLs with PII, or private message bodies. Short queue TTL."],
        ["feature_snapshot", "subject_id, artifact_id, model_version, encrypted_style_stats, encrypted_temporal_residuals, DEK_ref", "Private derived personal data; policy-bounded retention, e.g. rolling 18 months for detailed features."],
        ["longitudinal_state", "subject_id, semester, encrypted_mean, covariance, growth_velocity, provenance_mix", "Authorized 4-year aggregate trajectory plus a stated graduation grace period; withdrawal can delete it."],
        ["verification_result", "artifact_id, posterior, interval, decision, flag_codes, baseline/model/policy versions", "Private access by student and authorized course staff; no durable sensitive feature explanation."],
        ["credential_record", "random_credential_id, result_id, issuer_key_id, status_index, issue_at, expiry, revocation_state", "Private association to subject. Public registry has only proof/status material and no student mapping."],
        ["audit_event / purge_receipt", "opaque_job_id, control_version, action_code, timestamp, key_destroy_receipt", "No payloads; tamper-evident hash chain with access-controlled, policy-limited retention."],
      ] } },
      { title: "Where pgvector fits—and where it does not", body: [
        "The default mode discards per-sentence embeddings after computing within-box semantic drift and retains only encrypted aggregate state. pgvector is optional for institution-local prototype search, not a vendor-hosted memory of every paper. If approved, use vector(384) for bounded, provenance-filtered prototypes with explicit subject filters; for small per-student histories, exact cosine comparison is simpler and safer than a global HNSW index. No separate graph database is needed; the Bayesian DAG is model code.",
        "Do not claim application-encrypted vectors can be indexed normally by pgvector. Either decrypt a small feature set in the trusted worker and compare there, or approve plaintext-in-process/database-memory vectors within the isolated institutional service with encrypted disks, strong roles, and no public access. Random projections and clipped, quantized aggregates reduce leakage but still require reconstruction and membership-inference testing. Differential privacy is useful for released cohort analytics with an explicit epsilon/delta budget; it is not a blanket fix for an individual's authorship vector.",
      ] },
      { title: "Cryptography, lifetime, and verifiable purge controls", body: [
        "Use TLS 1.3 at ingress, mTLS between services, institutional OIDC with passkeys/MFA for privileged access, and least-privilege short-lived service identities. Envelope-encrypt derived state with AES-256-GCM under per-subject DEKs, with tenant KEKs in an institution-controlled KMS/HSM. Keep keys outside PostgreSQL. Rotate keys, separate duties, and require time-bounded audited break-glass approval. A key identifier is not a key.",
        "The worker streams raw text from the authoritative LMS into bounded memory/tmpfs, extracts all required features, then discards tokens, raw text, parser intermediates, and dense embeddings before committing the minimized result. Purging immediately after tokenization would be incorrect if later encoders still need the tokens: define the last dependent operation precisely. Job cancellation, timeout, failure, and consent withdrawal execute the same cleanup path. On retry, refetch from the authoritative source; never recover raw text from a queue.",
        "Disable swap, hibernation, core dumps, request-body logging, tracing payloads, and persistent temp directories. Use a read-only root filesystem, bounded tmpfs, disabled outbound DNS/network except allowlisted source endpoints, and separate trusted CPU/GPU pools. Destroy ephemeral worker processes between sensitive batches and clear accelerator buffers where supported. Managed runtimes, parser copies, GPU caches, and physical remanence prevent an absolute proof of instant RAM wiping; document that residual risk rather than pretending a finally block guarantees forensic erasure.",
        "For derived-data erasure, atomically withdraw consent and block fetch/commit, cancel queued work, delete snapshots/prototypes/identity mappings as authorized, revoke share handles, and cryptographically destroy the relevant DEK. Cover WAL, replicas, snapshots, and restored backups: use short expiry, separate key retention, and a deletion ledger replayed before restored systems serve traffic. Crypto-erasure fails if an old backup also contains a usable DEK, so test that condition. The original LMS retains its records under its own university policy; AuthWords cannot promise deletion there.",
      ], bullets: [
        "Write only content-free purge receipts, including job ID, container termination, DEK revocation where applicable, and cleanup outcome. A receipt records control execution, not a proof that no physical bit remains.",
        "An independent egress gateway validates the exact result schema, rejects free-form flags, caps precision and size, and uses an institution-scoped release policy. Canary text tests, packet captures, crash tests, and backup-restoration drills enforce the boundary continuously.",
        "No raw content enters backups, object stores, dead-letter queues, crash reporters, analytic trackers, support tools, or model-training exports. New local model training on baseline records requires a separately governed purpose; no cross-institution training is implicit.",
      ] },
    ],
  },
  {
    id: "lti", number: "04", shortTitle: "LTI & LMS pipeline", title: "Connected to learning. Not surveillance.",
    summary: "Standards-based identity and grade exchange, paired with honest platform-specific event ingestion.",
    tags: ["LTI 1.3 + Advantage", "OIDC / OAuth 2.0", "Asynchronous jobs"],
    blocks: [
      { title: "LTI 1.3 launch is not a submission webhook", body: [
        "LTI 1.3 standardizes tool launch, trust, and signed context; LTI Advantage adds Deep Linking, Names and Role Provisioning Services, and Assignment and Grade Services. It does not magically notify a tool of every native LMS essay, email, or discussion post. A cross-origin iframe cannot inspect the host LMS. AuthWords needs a locally deployed event adapter and separately scoped institution-approved API permissions for each source.",
      ], table: { headers: ["Platform", "Capture pathway", "Important constraint"], rows: [
        ["Canvas", "Institution-configured Live Events / Data Services where enabled, or institution-local REST reconciliation for submissions and discussion entries", "Delivery and licensing vary. LTI OAuth service tokens do not grant arbitrary Canvas REST access; provision separate scoped credentials."],
        ["Blackboard Learn", "Approved Learn REST integration with incremental reconciliation; event facilities only where that deployment supports them", "Do not assume a universal signed webhook. Validate permissions and version-specific assignment/discussion support."],
        ["Moodle", "Institution-installed local plugin observes submission/discussion events and writes a transactional local outbox; scoped web services fetch artifacts", "The university controls installation, supported event classes, retries, and the raw-content boundary."],
        ["AuthWords-hosted activity", "Deep-linked assignment receives the student's own submission directly inside the institutional deployment", "The tool owns its submission event, but must still verify consent, role, artifact type, and academic policy."],
      ] } },
      { title: "OIDC launch, step by step", body: [
        "1. Register the platform issuer, client ID, deployment IDs, authorization endpoint, token endpoint, exact redirect URIs, and JWKS URL through an administrator-approved trust record. Keep outbound hosts allowlisted to prevent SSRF and malicious discovery. Never trust a JWKS URL supplied by an arbitrary launch token.",
        "2. At login initiation, create a cryptographically random state and nonce with a short TTL and one-use server-side record. Bind them to the expected platform and browser flow. Request the LTI id_token using OIDC form_post. Handle iframe third-party-cookie restrictions with a supported top-level launch or standards-compliant storage flow; do not disable state validation to make embedding work.",
        "3. Validate the platform-signed JWT with jose and cached approved JWKS: allowed algorithm, signature, issuer, audience and azp when required, exp/iat, one-use nonce/state, deployment_id, LTI version, message_type, resource link, and role. Refresh a missing kid once with bounded fetches; reject algorithm confusion and replay. Map the subject to an institutional pseudonym only after validation.",
        "4. Establish a short-lived institution-local session with HttpOnly secure cookies, CSRF protection, strict frame-ancestors for approved LMS origins, and role-based course access. NRPS access is optional and least-privilege; do not import a whole roster merely because a scope is available. Present the consent screen before collecting a writing baseline.",
      ] },
      { title: "Capture → queue → analysis → private review", body: [
        "Authenticate an event using the source's documented signature, cloud-delivery identity, or institution-local mTLS plugin channel. A timestamp and event ID bound replay; not every LMS offers HMAC headers, so do not invent a universal signature format. Ignore user-supplied tenant/subject bindings and resolve them from trusted source configuration. Commit the idempotent inbox/outbox record and immediately acknowledge receipt; process asynchronously.",
        "BullMQ orchestrators claim only references. Inside the Secure Analysis Box, re-check consent and policy, obtain a short-lived source access token, fetch the authorized artifact, run the assignment-aware ensemble, execute the purge lifecycle, and atomically commit result plus grade-passback outbox. Cancelled or withdrawn jobs cannot commit. Reconciliation cursors detect missed events and delayed edits without duplicating results; a new artifact revision always has a new verification decision.",
      ], code: "event_received → consent_checked → queued → local_fetch\n→ feature_extraction → contextual_inference → raw_cleanup\n→ result_committed → optional_human_review → passback_pending\n→ passed_back\n\nAny stage: consent_revoked → cancel → purge → no disclosure\nTransient failure: retry opaque reference; never persist text" },
      { title: "AGS passback without turning probability into a grade", body: [
        "Discover the AGS endpoints and allowed scopes from the validated launch claim https://purl.imsglobal.org/spec/lti-ags/claim/endpoint. Use OAuth 2.0 client credentials with a short-lived, jti-protected private_key_jwt assertion and request only the granted score scope; lineitem scope is required if creating a separate column. Validate service endpoint hosts against the registered institution, and keep those tokens inside the local plane.",
        "The preferred display is an AuthWords LTI review panel beside the instructor's ordinary grade. If the university approves gradebook passback, create or reuse a dedicated zero-weight Authorship verification line item tagged to the resource, with scoreMaximum 1. Publish a numeric probability only in that clearly labeled diagnostic column, with a controlled explanatory comment and uncertainty in the private tool. Do not overwrite the academic grade, encode confidence as an earned mark, or automatically turn a regular A into a different numeric grade.",
        "POST application/vnd.ims.lis.v1.score+json to the validated lineitem URL plus /scores, including the correct LTI userId, timestamp, activityProgress Completed, and gradingProgress FullyGraded for a finalized diagnostic result or PendingManual for human review. Abstentions can omit scoreGiven; test platform-specific display behavior. The LMS may not support arbitrary badges or unweighted columns through AGS, so use the tool UI unless administrators explicitly configure the gradebook. Never promise a universal native Verified A decoration.",
        "Keep passback jobs versioned and ordered per (line item, student). Retry 429/5xx with jitter, refresh expired tokens, and do not let a stale revision overwrite a new result. Reuse existing resource/tag mappings on repeat launches and course copies. After consent withdrawal, clear or retract shared diagnostics where supported and reconcile local links; retain only the institution's lawful minimum audit record. The final academic grade remains the instructor's responsibility.",
      ] },
    ],
  },
  {
    id: "credentials", number: "05", shortTitle: "Cryptographic credentials", title: "Proof that opens doors. Not your data.",
    summary: "A tamper-evident, student-controlled authorship enhancement with minimal public claims and a clearly defined trust chain.",
    tags: ["W3C VC 2.0", "Asymmetric signatures", "Minimal disclosure"],
    blocks: [
      { title: "Separate the grade, the evidence, and the credential", body: [
        "A signed probability does not create an academic grade. The institutional credential service accepts an approved verification decision only after confirming the instructor's final grade, current consent, sufficient provenance, and the result's model/policy version. It binds that grade and narrowly scoped authorship claim to a random credential ID and a holder-controlled public key. Use an idempotency key per institution/artifact revision/credential type so retries cannot mint conflicting attestations.",
        "Adopt W3C Verifiable Credentials Data Model 2.0 with a pinned, interoperable VC-JOSE securing profile. In the Bun service, jose handles the JOSE layer; schema validation and VC semantics are separate responsibilities. Use ES256 through an institution-controlled PKCS#11 HSM, or Ed25519 with an appropriate institutional signing service whose key is nonexportable. Publish kid-versioned public keys; retain historical verification keys through credential expiry. Never embed a signing secret in the browser or use a shared HS256 secret with employers.",
        "The working reference app uses genuine Ed25519-signed JWTs and public JWKS, but is deliberately a synthetic demo—not a W3C-conformant credential issuer or academic authority. Its server-only demo key is stored locally in the demo database for persistence. That choice is unacceptable for production key custody and is not the HSM topology described above. Public demo pages explicitly state that neither a real grade nor holder identity is certified.",
      ] },
      { title: "Minimal claims and the issuer-privacy trade-off", body: [
        "The private institutional record binds the result, grade, rubric, artifact revision, and student. A public presentation can disclose only authorshipVerified=true, the student-authorized grade (or an even coarser achievement band), issuance/expiry at minimized precision, the applicable credential type, and a holder-binding key. It contains no student name, email, LMS ID, course, assignment title, paper hash, underlying evidence, institution identifier, or language-learning attributes. Raw-text hashes are avoided because candidate texts can be tested against them.",
        "An employer still needs a trusted issuer. If the university signs the public artifact directly, its public key usually identifies that school; pretending otherwise is not privacy engineering. To hide the school, use an explicitly governed AuthWords federation attester. The institution sends a minimal authenticated eligibility assertion, the federation verifies its authorization privately, and the federation issues a uniform public proof without school metadata. Employers then trust the federation's accreditation and audit policy rather than learning the underlying university. This is a product trust trade-off, not an anonymous proof of a named university degree.",
        "Keep model outputs private by default. Separately authorized sharing may release only the constrained probability/uncertainty and flags, with rounded precision and no evidence vectors. A credential's signed claim is a different, deliberately minimal disclosure path. Grade disclosure must also be explicit; if even the grade is unnecessary, share just the authorship enhancement. A probability is never evidence that a credential holder is honest in all future work.",
      ], code: "PRIVATE INSTITUTIONAL RECORD\nstudent ↔ assignment revision ↔ approved grade ↔ verified evidence\n                 ↓ minimal authenticated eligibility assertion\nFEDERATION ATTESTER (school mapping remains private)\n                 ↓ public, asymmetrically signed presentation\n{ issuer: federation, random_id, authorship_verified: true,\n  authorized_grade?: 'A', holder_key, expires, status_reference }\n\nNo name. No school. No course. No paper. No writing fingerprint." },
      { title: "Public verification and proof of possession", body: [
        "The student creates a high-entropy, unguessable share handle, ideally 256 random bits with only its keyed hash stored. Default to a short TTL, purpose-bound audience, and single use where useful. The public page loads only a minimal assertion. It sets noindex, no-referrer, no-store, no analytics, and no third-party assets; suppress share handles in access logs. Possessing the URL grants access, so a random URL is a capability, not authentication or a guarantee against forwarding.",
        "A verifier resolves the trusted issuer key from an allowlisted trust registry, verifies the algorithm and signature, validates type/claims, expiry, audience, and status, and displays precisely what was attested. For identity binding, issue a fresh nonce and audience challenge and require a short-lived holder-signed presentation using the credential's cnf key. The student separately supplies their identity through an employer-approved channel. A static URL or valid signature alone proves neither the visitor's identity nor possession by the named job applicant.",
        "Support user-controlled revocation and administrative correction without erasing historical key material needed to verify existing proofs. Use a W3C Bitstring Status List with sufficiently large, shared, randomized cohorts rather than a per-student tracking URL; cache or proxy list fetches. Verifiers check status freshness. A revoked credential can still have a mathematically valid old signature, which is why offline signature verification alone is insufficient. Reissue corrected credentials with new IDs; never resurrect a revoked artifact.",
      ] },
      { title: "Selective disclosure is not automatic unlinkability", body: [
        "Plain signed JWTs are readable and correlatable. SD-JWT can selectively disclose claims but a repeated issuer-signed base token or holder key can still correlate presentations. If cross-employer unlinkability becomes a requirement, evaluate a standardized BBS-based Data Integrity suite with compatible wallets and unlinkable derived proofs, key-binding support, and a tested status mechanism. Do not call a JWT zero knowledge, and do not add a blockchain containing student-linked records.",
        "Acceptance tests must include one-bit payload tampering, algorithm substitution, untrusted issuer, expired credential, revoked status, wrong audience, reused challenge, stolen share URL, key rotation, corrected grade, consent withdrawal, and a no-PII egress check. Test LMS and credential rollback independently. Launch only after institutional legal review, independent security assessment, representative model validation, and a student-accessible appeal process.",
      ] },
    ],
  },
];

export const blueprintSources = [
  { title: "TanStack Start · Hosting and Bun deployment", url: "https://tanstack.com/start/latest/docs/framework/react/guide/hosting" },
  { title: "Bun · Native TanStack Start integration", url: "https://bun.com/docs/guides/ecosystem/tanstack-start" },
  { title: "1EdTech · LTI 1.3 and LTI Advantage", url: "https://www.1edtech.org/standards/lti" },
  { title: "1EdTech · Assignment and Grade Services 2.0", url: "https://www.imsglobal.org/spec/lti-ags/v2p0" },
  { title: "Instructure · Canvas Live Events", url: "https://developerdocs.instructure.com/services/canvas/data-services/live-events" },
  { title: "W3C · Verifiable Credentials Data Model 2.0", url: "https://www.w3.org/TR/vc-data-model-2.0/" },
  { title: "W3C · Bitstring Status List v1.0", url: "https://www.w3.org/TR/vc-bitstring-status-list/" },
  { title: "Morris et al. · Text Embeddings Reveal (Almost) As Much As Text", url: "https://arxiv.org/abs/2310.06816" },
];

export function blueprintMarkdown() {
  return "# AuthWords — Production Architecture Blueprint\n\nVersion 1.0 · Reference design, not a compliance certification.\n\n" + blueprint.map(section =>
    `## ${section.number}. ${section.shortTitle}\n\n${section.title}\n\n${section.summary}\n\n` + section.blocks.map(block =>
      `### ${block.title}\n\n${block.body.join("\n\n")}\n\n` + (block.bullets ? block.bullets.map(b => `- ${b}`).join("\n") + "\n\n" : "") +
      (block.code ? "```text\n" + block.code + "\n```\n\n" : "") +
      (block.table ? "| " + block.table.headers.join(" | ") + " |\n| " + block.table.headers.map(() => "---").join(" | ") + " |\n" + block.table.rows.map(row => "| " + row.join(" | ") + " |").join("\n") + "\n\n" : "")
    ).join("")
  ).join("\n") + "## Primary sources\n\n" + blueprintSources.map(s => `- [${s.title}](${s.url})`).join("\n");
}
