"use client";
import { useMemo, useState } from "react";
import { ArrowRight, ArrowUpRight, TrendingUp, BadgeCheck, Fingerprint, FileText, Layers3, Plus, CalendarDays, Info, Search, ArrowDownToLine, ChevronLeft, ChevronRight, Check, ShieldCheck } from "lucide-react";
import { HeroArtwork, Sparkline, ConfidenceChart, RadarChart, CredentialMedallion } from "@/components/visuals";
import { StatusBadge, EmptyState } from "@/components/primitives";
import { formatDate, exportSubmissions, type View } from "@/lib/client";
import { sourceOptions, type WorkspaceData, type Submission } from "@/lib/demo-data";

export function SourceMark({ source }: { source: string }) {
  return <span className="source-label">{source === "Canvas" ? <svg width="15" height="15" viewBox="0 0 20 20" fill="none" aria-hidden="true"><circle cx="10" cy="10" r="6.5" stroke="#dc785c" strokeWidth="3.4" strokeDasharray="2 3.1"/><circle cx="10" cy="10" r="2" fill="#dc785c"/></svg> : <FileText size={14} color="#8c9580"/>}{source}</span>;
}

export function SubmissionTable({ rows, onSelect }: { rows: Submission[]; onSelect: (s: Submission) => void }) {
  return <div className="submission-table-wrap"><table className="submission-table"><thead><tr><th>Submission</th><th>Source</th><th>Submitted</th><th>Authorship confidence</th><th>Status</th><th><span className="sr-only">View</span></th></tr></thead><tbody>{rows.map((submission, index) => <tr key={submission.id} onClick={() => onSelect(submission)}><td><div className="submission-title-cell"><span className={`file-icon file-tone-${index % 4}`}><FileText size={17} strokeWidth={1.6}/></span><div><button className="table-title" onClick={event => { event.stopPropagation(); onSelect(submission); }}>{submission.title}</button><p>{submission.course}</p></div></div></td><td><SourceMark source={submission.source}/></td><td className="date-cell">{formatDate(submission.submittedAt)}</td><td><div className="table-confidence">{submission.score === null ? <span className="muted">Not enough evidence</span> : <><span>{submission.score.toFixed(1)}<small>%</small></span><div className={`mini-progress ${submission.status !== "Verified" ? "muted-progress" : ""}`}><span style={{ width: `${submission.score}%` }}/></div></>}</div></td><td><StatusBadge status={submission.status}/></td><td><button className="table-arrow" onClick={event => { event.stopPropagation(); onSelect(submission); }} aria-label={`View ${submission.title}`}><ArrowUpRight size={16}/></button></td></tr>)}</tbody></table></div>;
}

export function Overview({ data, onNavigate, onNew, onSelect }: { data: WorkspaceData; onNavigate: (view: View) => void; onNew: () => void; onSelect: (s: Submission) => void }) {
  const [period, setPeriod] = useState<"6m" | "1y">("6m");
  const verified = data.submissions.filter(s => s.status === "Verified");
  const confidence = verified.length ? (verified.reduce((sum, s) => sum + (s.score || 0), 0) / verified.length).toFixed(1) : "—";
  const samples = sourceOptions.filter(s => data.sources.includes(s.id)).reduce((sum, s) => sum + s.count, 0);
  const stats = [
    { title: "Verified submissions", value: verified.length, icon: BadgeCheck, note: "Your work, backed by trust", variant: 0, tone: "sage", view: "submissions" as View },
    { title: "Authorship confidence", value: confidence, suffix: "%", icon: Fingerprint, note: "A strong, consistent voice", variant: 1, tone: "sand", view: "profile" as View },
    { title: "Writing samples", value: samples, icon: Layers3, note: `${data.sources.length} sources, one unique you`, variant: 2, tone: "lavender", view: "profile" as View },
    { title: "Credentials earned", value: data.credentials.filter(c => !c.revoked).length, icon: FileText, note: "Ready for your next chapter", variant: 3, tone: "rose", view: "credentials" as View },
  ];
  return <>
    <div className="page-heading overview-heading"><div><h1>Your authorship, at a glance.</h1><p>A little more confidence in every word.</p></div><div className="heading-actions"><span className="semester"><CalendarDays size={15}/> Spring 2026</span><button className="button button-primary" onClick={onNew}><Plus size={16}/> Verify new work</button></div></div>
    <section className="welcome-banner"><div className="welcome-copy"><div className="eyebrow"><span className="tiny-star">✳</span> ORIGINAL THINKING. REAL OPPORTUNITY.</div><h2>Good work deserves<br/>to be <span>recognized.</span></h2><p>Curious? Try real public-domain writing. No account. No uploads.</p><a className="banner-link" href="/demo">Try the public demo <ArrowRight size={15}/></a></div><HeroArtwork/></section>
    <div className="stats-grid">{stats.map((stat, i) => { const Icon = stat.icon; return <button className="stat-card" key={stat.title} onClick={() => onNavigate(stat.view)}><div className="stat-top"><span>{stat.title}</span><span className={`stat-icon ${stat.tone}`}><Icon size={16} strokeWidth={1.6}/></span></div><div className="stat-value-row"><strong>{stat.value}<small>{stat.suffix}</small></strong><Sparkline variant={stat.variant} color={i === 2 ? "#a0a47e" : "#789154"}/></div><div className="stat-note">{i === 0 || i === 1 ? <TrendingUp size={12}/> : i === 3 ? <ArrowUpRight size={12}/> : <span className="small-dot"/>}<span>{stat.note}</span></div></button>; })}</div>
    <div className="overview-charts"><section className="card growth-card"><div className="card-heading"><div><h3>Your voice, over time <span className="info-label" title="An illustrative trend from a synthetic student profile. These are not validated model outputs."><Info size={13}/></span></h3><p>Every submission adds to your story.</p></div><div className="segmented-control"><button onClick={() => setPeriod("6m")} className={period === "6m" ? "active" : ""}>6 months</button><button onClick={() => setPeriod("1y")} className={period === "1y" ? "active" : ""}>1 year</button></div></div><ConfidenceChart period={period}/><div className="chart-footer"><span><i className="legend-dot"/> Authorship confidence</span><span><i className="legend-dash"/> Expected growth</span><span className="chart-growth"><TrendingUp size={12}/> Growing with you</span></div></section>
      <section className="card fingerprint-card"><div className="card-heading"><div><h3>Your writing fingerprint</h3><p>A pattern only your words can make.</p></div><Fingerprint size={18} className="muted"/></div><RadarChart/><div className="fingerprint-footer"><span>Distinctly you. Always evolving.</span><button className="text-button" onClick={() => onNavigate("profile")}>View your profile <ArrowRight size={13}/></button></div></section></div>
    <section className="card recent-card"><div className="card-heading"><div className="heading-with-label"><h3>Recent submissions</h3><span className="quiet-tag"><span className="green-dot"/> Up to date</span></div><button className="text-button" onClick={() => onNavigate("submissions")}>View all submissions <ArrowRight size={14}/></button></div><SubmissionTable rows={data.submissions.slice(0, 5)} onSelect={onSelect}/><div className="table-footer"><span>Showing 5 of {data.submissions.length} submissions</span><span><ShieldCheck size={12}/> Your story, securely held.</span></div></section>
    <section className="opportunity-banner"><div className="opportunity-icon"><CredentialMedallion compact/></div><div><h3>A grade tells a story. A verified grade proves it’s yours.</h3><p>Take your authentic work beyond the classroom.</p></div><button className="button button-light" onClick={() => onNavigate("credentials")}>Explore your credentials <ArrowUpRight size={15}/></button><div className="opportunity-lines"/></section>
  </>;
}

export function SubmissionsView({ data, onSelect, onNew }: { data: WorkspaceData; onSelect: (s: Submission) => void; onNew: () => void }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("All work");
  const [sort, setSort] = useState("newest");
  const [page, setPage] = useState(1);
  const rows = useMemo(() => data.submissions.filter(s => (status === "All work" || s.status === status) && `${s.title} ${s.course} ${s.source}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === "confidence" ? (b.score ?? -1) - (a.score ?? -1) : sort === "oldest" ? +new Date(a.submittedAt) - +new Date(b.submittedAt) : +new Date(b.submittedAt) - +new Date(a.submittedAt)), [data.submissions, status, query, sort]);
  const pages = Math.max(1, Math.ceil(rows.length / 10));
  const currentPage = Math.min(page, pages);
  return <><div className="page-heading"><div><h1>Every piece. Part of your story.</h1><p>A home for your submissions and the confidence behind them.</p></div><div className="heading-actions"><button className="button button-secondary" onClick={() => exportSubmissions(rows)}><ArrowDownToLine size={15}/> Export CSV</button><button className="button button-primary" onClick={onNew}><Plus size={16}/> Verify new work</button></div></div>
    <div className="submissions-summary"><span><FileText size={17}/><strong>{data.submissions.length}</strong> total submissions</span><span><BadgeCheck size={17}/><strong>{data.submissions.filter(s => s.status === "Verified").length}</strong> verified</span><span><Info size={17}/><strong>{data.submissions.filter(s => s.status !== "Verified").length}</strong> need a little more context</span><span className="summary-disclaimer">Synthetic demo records</span></div>
    <section className="card all-submissions"><div className="submissions-toolbar"><div className="filter-tabs">{["All work", "Verified", "Needs context", "Insufficient evidence"].map(filter => <button key={filter} className={status === filter ? "active" : ""} onClick={() => { setStatus(filter); setPage(1); }}>{filter}{status === filter && <span>{rows.length}</span>}</button>)}</div><div className="table-search-row"><div className="search-input"><Search size={15}/><input aria-label="Search submissions" placeholder="Search your work…" value={query} onChange={e => { setQuery(e.target.value); setPage(1); }}/></div><select aria-label="Sort submissions" className="sort-select" value={sort} onChange={e => { setSort(e.target.value); setPage(1); }}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="confidence">Highest confidence</option></select></div></div>
    {rows.length ? <SubmissionTable rows={rows.slice((currentPage - 1) * 10, currentPage * 10)} onSelect={onSelect}/> : <EmptyState title="No work found. A fresh page awaits." description="Try another title or course, or clear your filters to see all your work." action={<button className="button button-secondary" onClick={() => { setQuery(""); setStatus("All work"); }}>Clear filters</button>}/>}
    <div className="table-footer"><span>{rows.length ? `${(currentPage - 1) * 10 + 1}–${Math.min(currentPage * 10, rows.length)} of ${rows.length} submissions` : "0 submissions"}</span><div className="pagination"><button className="icon-button" aria-label="Previous page" disabled={currentPage <= 1} onClick={() => setPage(currentPage - 1)}><ChevronLeft size={16}/></button><span>Page {currentPage} of {pages}</span><button className="icon-button" aria-label="Next page" disabled={currentPage >= pages} onClick={() => setPage(currentPage + 1)}><ChevronRight size={16}/></button></div></div></section>
    <div className="bottom-explainer"><Check size={17}/><p><strong>Verification is an opportunity, not a verdict.</strong> A “Needs context” result never changes your ordinary grade.</p></div>
  </>;
}
