"use client";

import { useEffect, useRef, useState, type CSSProperties } from "react";
import { ArrowRight, ArrowUpRight, ArrowDownToLine, BookOpen, Check, ChevronDown, ChevronRight, CircleHelp, ClipboardCheck, ExternalLink, Feather, Fingerprint, FlaskConical, Globe2, Info, Layers3, LoaderCircle, LockKeyhole, Play, RotateCcw, ShieldCheck, Sparkles, Users, AlignLeft } from "lucide-react";
import Link from "next/link";
import { Brand } from "@/components/visuals";
import { Modal } from "@/components/primitives";
import { downloadFile } from "@/lib/client";
import { baselineExcerpts, comparePublicScenario, defaultScenarioId, featureDefinitions, publicCorpus, type DemoComparison, type PublicExcerpt } from "@/lib/public-demo";

const scenarioIcons = [Feather, Users, Sparkles, AlignLeft];
const flagLabels: Record<string, string> = {
  SMALL_REFERENCE_SET: "Small reference set", GENRE_AND_VOICE_SHIFT: "Genre & voice differ", MODERN_LANGUAGE_SHIFT: "Modern language", SINGLE_SYNTHETIC_EXAMPLE: "One AI example only", SHORT_SAMPLE: "Too few words", SPARSE_BASELINE: "More baseline needed",
};

export default function PublicDemo({ initialScenarioId = defaultScenarioId, initialBaselineIds = publicCorpus.baselineIds }: { initialScenarioId?: string; initialBaselineIds?: string[] }) {
  const [scenarioId, setScenarioId] = useState(initialScenarioId);
  const [selectedBaselineIds, setSelectedBaselineIds] = useState(initialBaselineIds);
  const [report, setReport] = useState<DemoComparison>(() => comparePublicScenario(initialScenarioId, initialBaselineIds));
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [preview, setPreview] = useState<PublicExcerpt | null>(null);
  const [sourcesOpen, setSourcesOpen] = useState(false);
  const [contextAuthor, setContextAuthor] = useState("jane-austen");
  const [showMetrics, setShowMetrics] = useState(false);
  const [announcement, setAnnouncement] = useState("");
  const requestRef = useRef<AbortController | null>(null);
  useEffect(() => () => requestRef.current?.abort(), []);

  const scenario = publicCorpus.scenarios.find(item => item.id === scenarioId)!;
  const sample = publicCorpus.excerpts.find(item => item.id === scenario.sampleId)!;
  const reportSample = publicCorpus.excerpts.find(item => item.id === report.sampleId)!;
  const referenceWords = baselineExcerpts.filter(item => selectedBaselineIds.includes(item.id)).reduce((sum, item) => sum + item.wordCount, 0);
  const author = publicCorpus.authors.find(item => item.id === contextAuthor)!;
  const selectionChanged = report.scenarioId !== scenarioId || [...report.baselineIds].sort().join() !== [...selectedBaselineIds].sort().join();
  const attributedAuthor = publicCorpus.authors.find(item => item.id === sample.authorId)?.name || "AI-generated fixture";

  function toggleBaseline(id: string) {
    if (busy) return;
    setSelectedBaselineIds(ids => ids.includes(id) ? ids.length === 1 ? ids : ids.filter(value => value !== id) : [...ids, id]);
    setError("");
  }
  async function run() {
    setBusy(true); setError(""); setAnnouncement("Calculating observable text features.");
    requestRef.current?.abort();
    const controller = new AbortController(); requestRef.current = controller;
    try {
      const query = new URLSearchParams({ scenario: scenarioId, baseline: selectedBaselineIds.join(",") });
      const response = await fetch(`/api/demo/compare?${query}`, { signal: controller.signal });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "The comparison could not be completed.");
      setReport(result);
      const shareQuery = new URLSearchParams({ sample: scenarioId });
      if (selectedBaselineIds.length !== publicCorpus.baselineIds.length) shareQuery.set("baseline", selectedBaselineIds.join(","));
      window.history.replaceState({}, "", `/demo?${shareQuery}`);
      setAnnouncement(`Comparison ready for ${sample.title}. ${result.score === null ? "Insufficient evidence; no score issued." : `Illustrative style index ${result.score} out of 100, not a probability.`}`);
    } catch (failure) {
      if (controller.signal.aborted) return;
      setError(failure instanceof Error ? failure.message : "Please try again.");
      setAnnouncement("The comparison could not be completed. You can retry.");
    } finally { if (!controller.signal.aborted) setBusy(false); }
  }
  function reset() {
    requestRef.current?.abort();
    setBusy(false); setError(""); setScenarioId(defaultScenarioId); setSelectedBaselineIds(publicCorpus.baselineIds);
    setReport(comparePublicScenario()); setShowMetrics(false); setContextAuthor("jane-austen");
    window.history.replaceState({}, "", "/demo"); setAnnouncement("Demo reset to the Austen holdout and all three references.");
  }
  function downloadReport() {
    downloadFile(JSON.stringify({ ...report, description: "Reproducible illustrative comparison. Not a credential, authorship probability, or AI-detection result.", formula: "score = round(100 / (1 + mean(abs(sample - baseline_mean) / sqrt(baseline_variance + floor^2))))", featureDefinitions, sourceHashes: publicCorpus.excerpts.filter(item => report.baselineIds.includes(item.id) || item.id === report.sampleId).map(item => ({ id: item.id, sha256: item.sha256, sourceUrl: item.sourceUrl })) }, null, 2), `authwords-${report.scenarioId}-comparison.json`, "application/json");
  }

  return <div className="pd-page">
    <header className="pd-header"><div className="pd-header-inner"><Link href="/" aria-label="AuthWords home"><Brand/></Link><span className="pd-header-separator"/><span className="pd-header-label">The public demo</span><nav aria-label="Public demo navigation"><Link href="/?view=blueprint" className="pd-blueprint-link">Read the blueprint <ArrowUpRight size={13}/></Link><Link href="/" className="button button-secondary">Explore workspace <ArrowRight size={14}/></Link></nav></div></header>
    <main className="pd-main" id="main-content">
      <section className="pd-hero"><div className="pd-hero-copy"><div className="pd-kicker"><span className="green-dot"/> REAL WORDS. NO SIGN-UP.</div><h1>A familiar author.<br/>A <em>better question.</em></h1><p>Would this passage fit Jane Austen’s writing history?<br className="pd-desktop-break"/> Watch a simple style index try, and see exactly where it fails. Real public-domain excerpts, not pretend data.</p><div className="pd-guest-promises"><span><Check size={13}/> No account</span><span><Check size={13}/> No uploads</span><span><Check size={13}/> Ready to explore</span></div><div className="pd-hero-actions"><a href="#comparison-lab" className="button button-primary"><Play size={13} fill="currentColor"/> Explore the comparison <ArrowRight size={14}/></a><button className="text-button" onClick={() => setSourcesOpen(true)}>Meet the source texts <BookOpen size={14}/></button></div></div>
        <div className="pd-book-art" aria-hidden="true"><div className="pd-art-orbit"/><span className="pd-art-star">✳</span><div className="pd-book pd-book-back"><div className="pd-book-rule"/><span>JANE AUSTEN</span><strong>Mansfield<br/>Park</strong><small>1814</small><div className="pd-book-rule"/></div><div className="pd-book pd-book-middle"><div className="pd-book-rule"/><span>JANE AUSTEN</span><strong>Pride &<br/>Prejudice</strong><small>1813</small><div className="pd-book-rule"/></div><div className="pd-book pd-book-front"><div className="pd-book-rule"/><span>JANE AUSTEN</span><strong>Sense &<br/>Sensibility</strong><Feather size={29} strokeWidth={1}/><small>1811</small><div className="pd-book-rule"/></div><div className="pd-art-proof"><BookOpen size={14}/><span>Old words. A new perspective.</span></div></div>
      </section>

      <div className="pd-demo-boundary"><FlaskConical size={17}/><p><strong>A small, honest experiment.</strong> The text is real; the comparison is illustrative. No trained model, AI verdict, or academic credential is produced. The surprising result is the lesson: scroll to the scoreboard.</p><span>PUBLIC COLLECTION · V1</span></div>
      <div className="pd-lab-heading" id="comparison-lab"><div><span className="eyebrow">THE AUTHORSHIP LAB</span><h2>Try the question for yourself.</h2></div><div className="pd-lab-actions"><button className="text-button" onClick={reset} disabled={busy}><RotateCcw size={13}/> Reset demo</button><a className="button button-secondary" href="/api/demo/corpus" download><ArrowDownToLine size={14}/> Download seed data</a></div></div>
      <div className="pd-lab-grid">
        <section className="card pd-baseline"><div className="pd-section-heading"><span className="pd-step">01</span><div><h3>Start with a known voice</h3><p>The reference baseline</p></div><Fingerprint size={19}/></div><div className="pd-author"><span className="pd-author-avatar">ja<span>✳</span></span><div><h4>Jane Austen</h4><p>English novelist · 1775–1817</p></div><span className="pd-author-badge"><Feather size={13}/></span></div><p className="pd-baseline-intro">Three different books. One published author. Choose which excerpts contribute.</p><div className="pd-reference-list">{baselineExcerpts.map((excerpt, index) => <div className={`pd-reference ${selectedBaselineIds.includes(excerpt.id) ? "selected" : ""}`} key={excerpt.id}><label><input type="checkbox" checked={selectedBaselineIds.includes(excerpt.id)} onChange={() => toggleBaseline(excerpt.id)} disabled={busy || (selectedBaselineIds.length === 1 && selectedBaselineIds.includes(excerpt.id))} aria-label={`Include ${excerpt.title}`}/><span className={`pd-tiny-book pd-book-tone-${index}`}><BookOpen size={17} strokeWidth={1.3}/></span><span><strong>{excerpt.title}</strong><small>{excerpt.year} <span>·</span> {excerpt.wordCount.toLocaleString()} words</small></span></label><button className="icon-button" onClick={() => setPreview(excerpt)} aria-label={`Read ${excerpt.title} reference`}><ArrowUpRight size={15}/></button></div>)}</div><div className="pd-baseline-stats"><div><strong>{selectedBaselineIds.length}<span>/ 3</span></strong><small>reference excerpts</small></div><div><strong>{referenceWords.toLocaleString()}</strong><small>words in the baseline</small></div></div><div className="pd-baseline-footnote"><LockKeyhole size={14}/><p>Bundled with this app. No student records or live source connection.</p></div><button className="pd-context-jump" onClick={() => document.getElementById("author-context")?.scrollIntoView({ behavior: "smooth", block: "start" })}><Globe2 size={14}/> Explore documented context <ArrowRight size={13}/></button></section>

        <section className="card pd-candidate"><div className="pd-section-heading"><span className="pd-step">02</span><div><h3>Choose a passage to compare</h3><p>Known sources. Different scenarios.</p></div></div><div className="pd-scenarios" role="group" aria-label="Comparison scenarios">{publicCorpus.scenarios.map((item, index) => { const Icon = scenarioIcons[index]; return <button key={item.id} className={scenarioId === item.id ? "active" : ""} aria-pressed={scenarioId === item.id} disabled={busy} onClick={() => { setScenarioId(item.id); setError(""); }}><Icon size={14}/>{item.label}</button>; })}</div>
          <div className="pd-passage-heading"><div><span className={`pd-sample-kind ${sample.role === "synthetic" ? "synthetic" : ""}`}>{sample.role === "synthetic" ? "AI-GENERATED · EXPLICITLY LABELED" : sample.role === "other-human" ? "OTHER HUMAN · NOT AI" : "HELD OUT · NEVER IN THE BASELINE"}</span><h3>{sample.title}<span>{sample.year || "Fixture v1"}</span></h3><p>{attributedAuthor}<span>·</span>{sample.wordCount.toLocaleString()} words<span>·</span>{sample.role === "synthetic" ? "Frozen output" : "Original English"}</p></div><button className="icon-button" onClick={() => setPreview(sample)} aria-label={`Read full ${sample.title} excerpt`}><BookOpen size={18}/></button></div>
          <div className={`pd-passage ${sample.role === "synthetic" ? "pd-passage-synthetic" : ""}`} tabIndex={0} role="region" aria-label={`${sample.title} excerpt`}>{sample.text.split("\n\n").map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div>
          <div className="pd-candidate-footer"><p><Info size={13}/>{scenario.summary}</p><div><span><ShieldCheck size={13}/> No upload. Just reference IDs.</span><button className="button button-primary" onClick={run} disabled={busy}>{busy ? <LoaderCircle size={14} className="spin"/> : <Fingerprint size={15}/>} {busy ? "Comparing…" : "Run comparison"}<ArrowRight size={14}/></button></div></div>
        </section>
      </div>
      {error && <div className="form-error pd-run-error" role="alert">{error} <button className="text-button" onClick={run}>Try again <ArrowRight size={12}/></button></div>}
      <span className="sr-only" role="status" aria-live="polite">{announcement}</span>

      <section className={`card pd-report ${selectionChanged ? "pd-report-stale" : ""}`} aria-label="Comparison result" aria-busy={busy}>
        <div className="pd-section-heading"><span className="pd-step">03</span><div><h3>Look at the evidence. Keep the context.</h3><p>{selectionChanged ? "Your selection changed. Run the comparison to update this result." : `Ready to inspect · ${reportSample.title} against ${report.baselineIds.length} reference excerpts`}</p></div><span className="pd-illustrative-label"><FlaskConical size={12}/>{selectionChanged ? "PREVIOUS RESULT" : "ILLUSTRATIVE ONLY"}</span></div>
        <div className="pd-report-body"><div className="pd-result-score"><div className={`pd-score-ring ${report.score === null ? "no-score" : ""}`} style={{ "--pd-score": `${(report.score || 0) * 3.6}deg` } as CSSProperties}><div>{report.score === null ? <CircleHelp size={37} strokeWidth={1.2}/> : <><strong>{report.score}</strong><span>/ 100</span></>}</div></div><div><h4>{report.score === null ? "Insufficient evidence" : "Observable style index"}</h4><p>{report.score === null ? "No score is the honest result." : "A distance display. Not a probability."}</p></div></div><div className="pd-result-explanation"><h4>{report.score === null ? "Known author. Not enough evidence." : "A comparison, not a conclusion."}</h4><p>{report.explanation}</p><div className="pd-result-flags">{report.flags.map(flag => <span key={flag}><Info size={10}/>{flagLabels[flag] || flag}</span>)}</div><div className="pd-ground-truth"><ClipboardCheck size={15}/><p><strong>{report.knownSource}.</strong> This is documented source metadata, not a finding from the score.</p></div></div></div>
        <div className="pd-result-bottom"><span><Layers3 size={13}/>{report.score === null ? "Comparison withheld" : `${report.windowWords} words inspected per excerpt · 6 equally weighted features`}</span><div>{report.features.length > 0 && <button className="text-button" onClick={() => setShowMetrics(!showMetrics)} aria-expanded={showMetrics} aria-controls="pd-feature-table">{showMetrics ? "Hide" : "Inspect"} the signals <ChevronDown size={13} className={showMetrics ? "pd-rotated" : ""}/></button>}<button className="text-button" onClick={downloadReport} disabled={busy || selectionChanged}><ArrowDownToLine size={13}/> Export result</button></div></div>
        {showMetrics && report.features.length > 0 && <div className="pd-metrics" id="pd-feature-table"><table><caption>Measured features from the selected text windows. Biographical and demographic fields are not inputs.</caption><thead><tr><th>Observable signal</th><th>Reference mean</th><th>This passage</th><th>Normalized difference</th></tr></thead><tbody>{report.features.map(feature => <tr key={feature.key}><td><strong>{feature.label}</strong><span>{feature.detail}</span></td><td>{feature.baseline.toFixed(feature.key === "sentenceRhythm" ? 2 : 1)} <small>{feature.unit}</small></td><td>{feature.sample.toFixed(feature.key === "sentenceRhythm" ? 2 : 1)} <small>{feature.unit}</small></td><td><div className="pd-residual"><span><i style={{ width: `${Math.min(100, feature.residual / 3 * 100)}%` }}/></span><strong>{feature.residual.toFixed(2)}</strong></div></td></tr>)}</tbody></table></div>}
      </section>

      <Scoreboard baselineIds={report.baselineIds} activeScenarioId={report.scenarioId}/>

      <div className="pd-bottom-grid"><section className="card pd-context-card" id="author-context"><div className="pd-section-heading"><span className="pd-context-icon"><Globe2 size={20}/></span><div><h3>Context, without assumptions.</h3><p>Usable metadata. Honest gaps.</p></div><span className="pd-context-tag">NOT SCORED</span></div><div className="pd-author-tabs" role="group" aria-label="Author context">{publicCorpus.authors.map(item => <button key={item.id} aria-pressed={contextAuthor === item.id} className={contextAuthor === item.id ? "active" : ""} onClick={() => setContextAuthor(item.id)}>{item.name}</button>)}</div><dl className="pd-context-fields"><div><dt>Writing language <span>Documented</span></dt><dd>{author.language}<a href={author.languageSourceUrl} target="_blank" rel="noopener noreferrer" aria-label={`Language source for ${author.name}`}><ExternalLink size={11}/></a></dd><small>Source-text language, not an L1 / L2 label.</small></div><div><dt>Birthplace <span>Documented</span></dt><dd>{author.region}</dd><small>Biographical context, not a demographic prior.</small></div><div><dt>Historical period <span>Documented</span></dt><dd>{author.lifespan}</dd><small>Publication dates are not a learning trajectory.</small></div><div><dt>ESL history <span className="pd-unknown">Unknown</span></dt><dd>Not documented</dd><small>Never inferred from a name or birthplace.</small></div><div><dt>Language proficiency <span className="pd-unknown">Unknown</span></dt><dd>Not assessed</dd><small>No CEFR level or growth curve is fabricated.</small></div><div><dt>Student cohort <span className="pd-unknown">Not available</span></dt><dd>Not a student dataset</dd><small>No demographic fairness claim can be made.</small></div></dl><div className="pd-context-footer"><p><ShieldCheck size={13}/> These fields explain context. They never change the index.</p><a className="text-button" href={author.biographyUrl} target="_blank" rel="noopener noreferrer">Biographical source <ExternalLink size={12}/></a></div></section>
        <section className="card pd-method-card"><div className="pd-section-heading"><span className="pd-context-icon"><FlaskConical size={20}/></span><div><h3>Small on purpose. Open to inspection.</h3><p>What you’re evaluating—and what you aren’t.</p></div></div><div className="pd-method-copy"><p>This demo replaces anonymous placeholder prose with a tiny, reproducible reference collection. It demonstrates the product’s question—not the accuracy of a production model.</p><details><summary>How is the number calculated?<ChevronDown size={14}/></summary><div><p>Compare equal leading windows of up to 250 words across the chosen excerpts. Measure six signals, take their reference means and variances, and average normalized absolute differences.</p><code>index = round(100 / (1 + mean distance))</code><p>Fixed scale floors reduce instability. The formula and floors are included in result exports. They are engineering choices, not statistically fitted thresholds. No semantics model, Bayesian calibration, or demographic classifier runs here.</p></div></details><details><summary>What can this collection not tell us?<ChevronDown size={14}/></summary><div><ul>{publicCorpus.limits.map(limit => <li key={limit}>{limit}</li>)}</ul><p>No index triggers a credential or misconduct decision.</p></div></details><details><summary>Why Austen—not Asimov or Frege?<ChevronDown size={14}/></summary><div><p>Austen’s selected English works have clear U.S. public-domain source records. We do not assume Asimov’s works are public domain. Frege’s original works may be usable, but a specific edition and any translation require separate rights and language checks.</p><p>The historical snippets exclude introductions, illustrations, and license boilerplate. Source attribution appears in the references. Check local copyright law outside the United States.</p></div></details><div className="pd-method-links"><button className="text-button" onClick={() => setSourcesOpen(true)}>Collection & source notes <BookOpen size={13}/></button><Link className="text-button" href="/?view=blueprint">Production architecture <ArrowUpRight size={13}/></Link></div></div></section>
      </div>
      <div className="pd-final-note"><ShieldCheck size={18}/><p><strong>Different is not dishonest.</strong> A student’s language, learning, genre, and permitted tools belong in the context—not in an accusation.</p><Link href="/?view=why-not-detection">Why we flipped the question <ArrowRight size={13}/></Link></div>
    </main>
    <footer className="pd-footer"><span>AuthWords · Your voice matters.</span><span>Public excerpts + one labeled AI fixture <span>·</span> No personal data requested</span><button onClick={() => setSourcesOpen(true)}>Sources & reuse <ExternalLink size={11}/></button></footer>
    {preview && <Modal title={preview.title} subtitle={preview.edition} onClose={() => setPreview(null)} wide><div className="pd-source-preview-meta"><span>{publicCorpus.authors.find(item => item.id === preview.authorId)?.name || "AI-generated fixture"}</span><span>{preview.year || "Frozen v1"}</span><span>{preview.wordCount} words</span></div><div className="pd-source-text">{preview.text.split("\n\n").map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div><div className="pd-source-footnote"><p>{preview.sourceNote}</p><p>{preview.rights}</p>{preview.generationPrompt && <details><summary>Generation prompt & provenance <ChevronDown size={13}/></summary><p>{preview.generationPrompt}</p><p>Generator: implementation assistant. Exact model identifier and random seed unavailable. The stored output and hash—not the generation process—are reproducible.</p></details>}<code>SHA-256: {preview.sha256}</code><div>{preview.sourceUrl && <a className="text-button" href={preview.sourceUrl} target="_blank" rel="noopener noreferrer">Source reference <ExternalLink size={12}/></a>}{preview.originalTextUrl && <a className="text-button" href={preview.originalTextUrl} target="_blank" rel="noopener noreferrer">Original full text <ExternalLink size={12}/></a>}</div></div><div className="modal-actions"><button className="button button-secondary" onClick={() => setPreview(null)}>Back to the demo</button></div></Modal>}
    {sourcesOpen && <Modal title="A small collection. A clear paper trail." subtitle="Versioned locally, with source notes and reproducible excerpt hashes." onClose={() => setSourcesOpen(false)} wide><div className="pd-sources-notice"><BookOpen size={18}/><p>{publicCorpus.rightsScope} These are excerpts of original English works, not modern translations.</p></div><div className="pd-source-list">{publicCorpus.excerpts.filter(item => !item.derivedFrom).map(excerpt => <article key={excerpt.id}><div><h3>{excerpt.title}</h3><span>{excerpt.year || "Synthetic fixture"} · {excerpt.wordCount} words · {excerpt.role === "baseline" ? "Reference" : "Test case"}</span></div><p>{excerpt.edition}</p><p>{excerpt.sourceNote}</p><div className="pd-source-links">{excerpt.sourceUrl ? <><a href={excerpt.sourceUrl} target="_blank" rel="noopener noreferrer">Catalog & rights <ExternalLink size={11}/></a><a href={excerpt.originalTextUrl!} target="_blank" rel="noopener noreferrer">Full source text <ExternalLink size={11}/></a></> : <span>New AI-generated text. No archive attribution. Prompt included in download.</span>}</div><code title={excerpt.sha256}>SHA-256 {excerpt.sha256}</code></article>)}</div><div className="pd-source-footnote"><p>{publicCorpus.acknowledgement}</p><a className="text-button" href={publicCorpus.sourcePolicyUrl} target="_blank" rel="noopener noreferrer">Archive reuse policy <ExternalLink size={12}/></a><p>The short-sample scenario reuses the first paragraph of the Emma holdout. Neither version enters the baseline. This intentionally public corpus is separate from the local-only student-data architecture.</p></div><div className="modal-actions"><button className="button button-secondary" onClick={() => setSourcesOpen(false)}>Close sources</button><a className="button button-primary" href="/api/demo/corpus" download><ArrowDownToLine size={15}/> Download full seed manifest</a></div></Modal>}
  </div>;
}

// Every scenario scored against the same references, side by side, with the honest reading.
function Scoreboard({ baselineIds, activeScenarioId }: { baselineIds: string[]; activeScenarioId: string }) {
  const rows = publicCorpus.scenarios.map(scenario => ({ scenario, result: comparePublicScenario(scenario.id, baselineIds) }));
  const same = rows.find(row => row.scenario.id === "same-author")!.result.score;
  const other = rows.find(row => row.scenario.id === "other-human")!.result.score;
  const ai = rows.find(row => row.scenario.id === "ai-fixture")!.result;
  const wordLength = ai.features.find(feature => feature.key === "wordLength");
  const sparse = same === null;
  const otherWins = !sparse && other !== null && other >= same;
  return <section className="card pd-scoreboard" aria-label="All scenarios compared">
    <div className="pd-section-heading"><span className="pd-step">04</span><div><h3>Now look at all four together.</h3><p>Every passage scored against the same {baselineIds.length} reference excerpt{baselineIds.length === 1 ? "" : "s"}. This is the part worth remembering.</p></div><span className="pd-illustrative-label"><FlaskConical size={12}/>THE HONEST READING</span></div>
    <div className="pd-scoreboard-grid">{rows.map(({ scenario, result }) => <div key={scenario.id} className={`pd-score-tile ${scenario.id === activeScenarioId ? "active" : ""} ${result.score === null ? "no-score" : ""}`}><span className="eyebrow">{scenario.label.toUpperCase()}</span><strong>{result.score === null ? "—" : result.score}</strong><small>{result.score === null ? "No score. Honest abstention." : scenario.truth.replace("Published attribution: ", "")}</small></div>)}</div>
    <div className="pd-scoreboard-reading">{sparse ? <p><strong>One reference is not a baseline.</strong> Restore a second excerpt and the scoreboard fills in. Abstaining here is the correct answer, not a missing feature.</p> : otherWins ? <p><strong>Mary Shelley scores at least as close to Austen as Austen’s own held-out chapter.</strong> Six surface features cannot tell two Regency-era novelists apart. This is exactly why no production decision in the AuthWords design rests on a style score alone: style is context, and supervised, attributable writing is the evidence.</p> : <p><strong>With these references the held-out chapter edges out Shelley, but only just.</strong> Change the selection above and the order can flip. A margin that small is not evidence of anything, which is why the production design treats style as context rather than verdict.</p>}
      {ai.score !== null && wordLength && <p><strong>The AI fixture looks far away mostly because it is modern English.</strong> Its largest normalized difference is word length{wordLength ? ` (${wordLength.residual.toFixed(2)})` : ""}, a signal about vocabulary and era, not about who or what wrote it. A model prompted to imitate Austen would close that gap.</p>}
      <p>Different is not dishonest, and similar is not proof. Read how the design answers this in <Link href="/?view=why-not-detection">Why not detection?</Link> and <Link href="/?view=flip">Flip the assignment</Link>.</p></div>
  </section>;
}
