"use client";
import { useState } from "react";
import { ArrowRight, ArrowUpRight, ArrowDownToLine, Check, Fingerprint, ShieldCheck, LockKeyhole, BookOpen, FileText, MessageSquare, Timer, Users, Mail, Search, BadgeCheck, ExternalLink, LoaderCircle, Info, Trash2, Sparkles, Layers3, Network, ChevronRight, Plus } from "lucide-react";
import { ConfidenceChart, RadarChart, CredentialMedallion } from "@/components/visuals";
import { EmptyState, DemoNotice } from "@/components/primitives";
import { api, downloadFile, formatDate, type View } from "@/lib/client";
import { sourceOptions, type WorkspaceData, type Submission } from "@/lib/demo-data";

interface PageProps { data: WorkspaceData; onNavigate: (view: View) => void }
const sourceIcons = [MessageSquare, Timer, FileText, Users, Layers3, Mail];

export function ProfileView({ data, onNavigate }: PageProps) {
  const [period, setPeriod] = useState<"6m" | "1y">("1y");
  const activeSources = sourceOptions.filter(source => data.sources.includes(source.id));
  const sampleCount = activeSources.reduce((sum, source) => sum + source.count, 0);
  return <><div className="page-heading"><div><h1>A voice that’s uniquely yours.</h1><p>Your writing changes as you grow. Your profile grows with it.</p></div><button className="button button-secondary" onClick={() => downloadFile(JSON.stringify({ type: "SyntheticAuthWordsProfile", demo: true, baselineSamples: sampleCount, enabledSources: data.sources, observedMetrics: data.submissions.map(s => ({ id: s.id, mode: s.mode, features: s.features, submittedAt: s.submittedAt })) }, null, 2), "authwords-demo-writing-profile.json", "application/json")}><ArrowDownToLine size={15}/> Export profile</button></div>
    <div className="profile-callout"><span className="profile-fingerprint"><Fingerprint size={34} strokeWidth={1.3}/></span><div><span className="eyebrow">YOUR WRITING DNA</span><h3>Not a fixed fingerprint. A living story.</h3><p>Built from {sampleCount} synthetic writing samples across {activeSources.length} source types. New genres and new skills are part of the picture.</p></div><span className="profile-version">PROFILE V1.0 <span className="green-dot"/></span></div>
    <div className="profile-grid"><section className="card large-radar-card"><div className="card-heading"><div><h3>The shape of your voice</h3><p>A five-dimensional, illustrative profile.</p></div><Fingerprint size={20}/></div><RadarChart large/><div className="radar-legend"><span><i className="legend-dot"/> Current profile</span><span><i className="legend-dash"/> Previous semester</span></div><p className="profile-card-note">Different is not suspicious. Context makes the difference.</p></section><section className="card profile-growth"><div className="card-heading"><div><h3>Room to grow. Space to be you.</h3><p>Illustrative longitudinal confidence</p></div><div className="segmented-control"><button className={period === "6m" ? "active" : ""} onClick={() => setPeriod("6m")}>6 months</button><button className={period === "1y" ? "active" : ""} onClick={() => setPeriod("1y")}>1 year</button></div></div><div className="profile-growth-number">98.6<span>%</span><span className="growth-pill">+6.5 pts this semester</span></div><ConfidenceChart period={period}/><div className="growth-context"><ShieldCheck size={17}/><p>Production models compare you with your own evolving history—not a single “ideal” way to write.</p></div></section></div>
    <div className="profile-bottom-grid"><section className="card baseline-card"><div className="card-heading"><div><h3>A baseline built on your terms</h3><p>You choose what contributes to your writing profile.</p></div><button className="text-button" onClick={() => onNavigate("settings")}>Manage sources <ArrowRight size={14}/></button></div><div className="baseline-sources">{sourceOptions.slice(0, 4).map((source, i) => { const Icon = sourceIcons[i]; const enabled = data.sources.includes(source.id); return <div key={source.id} className="baseline-source"><span className={`source-icon source-tone-${i}`}><Icon size={18}/></span><div><strong>{source.title}</strong><div className="source-progress"><span style={{ width: `${enabled ? source.count / 58 * 100 : 0}%` }}/></div></div><span className="source-count">{enabled ? source.count : 0}<small>samples</small></span></div>; })}</div></section><section className="card context-card"><span className="context-art"><BookOpen size={30} strokeWidth={1.4}/><Sparkles size={18}/></span><h3>There’s more to your voice<br/>than a pattern.</h3><p>Learning a new language? Exploring a new discipline? Your writing should change. Our blueprint accounts for language development, permitted tools, and long-term growth.</p><div className="context-promise"><Check size={14}/> No ethnicity or nationality inference</div><div className="context-promise"><Check size={14}/> No penalty for missing context</div><button className="text-button" onClick={() => onNavigate("blueprint")}>Explore the fairness safeguards <ArrowRight size={14}/></button></section></div>
  </>;
}

export function CredentialsView({ data, onShare, onSelect }: { data: WorkspaceData; onShare: (id: string) => void; onSelect: (s: Submission) => void }) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("active");
  const [limit, setLimit] = useState(6);
  const items = data.credentials.map(c => ({ ...c, submission: data.submissions.find(s => s.id === c.submissionId) })).filter(c => (filter === "all" || (filter === "active" ? !c.revoked : c.revoked)) && (c.submission?.title || "").toLowerCase().includes(query.toLowerCase()));
  const eligible = data.submissions.filter(s => s.status === "Verified" && !data.credentials.some(c => c.submissionId === s.id));
  return <><div className="page-heading"><div><h1>Your hard work. An added advantage.</h1><p>Proof of your originality, ready for wherever life takes you next.</p></div><span className="credential-count"><BadgeCheck size={16}/>{data.credentials.filter(c => !c.revoked).length} active credentials</span></div>
    <div className="credential-hero"><div><span className="eyebrow">MORE THAN A LETTER ON A TRANSCRIPT</span><h2>A regular A says you know it.<br/>A verified A says it’s yours.</h2><p>Share a signed, independently checkable demo credential.<br/>Your writing and your private academic details stay out of the picture.</p><div className="credential-hero-features"><span><LockKeyhole size={13}/> Privacy-preserving</span><span><BadgeCheck size={13}/> Cryptographically signed</span><span><Check size={13}/> Yours to share</span></div></div><CredentialMedallion/></div>
    <div className="credential-toolbar"><div className="filter-tabs">{[["active", "Active credentials"], ["revoked", "Revoked"], ["all", "All credentials"]].map(([value, label]) => <button key={value} className={filter === value ? "active" : ""} onClick={() => { setFilter(value); setLimit(6); }}>{label}</button>)}</div><div className="search-input"><Search size={15}/><input aria-label="Search credentials" value={query} onChange={e => { setQuery(e.target.value); setLimit(6); }} placeholder="Find a credential…"/></div></div>
    {items.length === 0 ? <div className="card"><EmptyState title={filter === "revoked" ? "No revoked credentials" : "No matching credentials"} description={filter === "revoked" ? "Revoked proofs will appear here. You stay in control of every share." : "Try a different search, or mint a credential for one of your verified submissions."}/></div> : <div className="credential-grid">{items.slice(0, limit).map((credential, i) => <article className={`credential-card ${credential.revoked ? "is-revoked" : ""}`} key={credential.id}><div className={`credential-card-art credential-art-${i % 3}`}><span>AUTHWORDS<br/><strong>VERIFIED AUTHORSHIP</strong></span><CredentialMedallion compact/><div className="credential-art-lines"/></div><div className="credential-card-body"><div className="credential-status"><span className={credential.revoked ? "muted" : "green-text"}>{credential.revoked ? "Revoked" : <><BadgeCheck size={13}/> Verified · Grade A</>}</span><span>DEMO</span></div><h3>{credential.submission?.title || "Verified submission"}</h3><p>{credential.submission?.course}</p><div className="credential-card-footer"><span>{formatDate(credential.createdAt)}</span><button className="text-button" onClick={() => onShare(credential.id)}>View credential <ArrowUpRight size={14}/></button></div></div></article>)}</div>}
    {items.length > limit && <div className="load-more"><button className="button button-secondary" onClick={() => setLimit(limit + 6)}>Show more credentials <Plus size={15}/></button><span>Showing {limit} of {items.length}</span></div>}
    {eligible.length > 0 && <section className="card eligible-card"><div><span className="stat-icon sage"><BadgeCheck size={21}/></span><div><h3>{eligible.length} more pieces of work are ready to stand out.</h3><p>Explore a verified submission and mint its demo credential.</p></div></div><button className="button button-secondary" onClick={() => onSelect(eligible[0])}>View eligible work <ArrowRight size={15}/></button></section>}
    <DemoNotice>These real digital signatures attest only to synthetic demo claims. They do not certify an academic grade, a real student, or holder identity.</DemoNotice>
  </>;
}

export function HowItWorksView({ onNavigate, onNew }: { onNavigate: (view: View) => void; onNew: () => void }) {
  const steps = [
    { icon: ShieldCheck, label: "Your choice comes first.", title: "Opt in. On your terms.", body: "Choose whether to participate and which sources can contribute. Your regular grade is never reduced if you opt out. Academic email is off by default.", tag: "01 · CONSENT" },
    { icon: Fingerprint, label: "More than a final draft.", title: "Build a picture of your voice.", body: "Authenticated discussions, in-class writing, drafts, and peer reviews build a rich, longitudinal baseline. Only attributable, authorized work belongs in the picture.", tag: "02 · BASELINE" },
    { icon: LockKeyhole, label: "Private by architecture.", title: "Compare locally. Consider context.", body: "The production Secure Analysis Box evaluates style, semantics, learning context, and growth inside the institution. A mismatch asks for context—it does not accuse.", tag: "03 · VERIFICATION" },
    { icon: BadgeCheck, label: "An advantage you can carry.", title: "Take your proof with you.", body: "An approved result can add an authorship enhancement to a grade. You decide what to share. A verifier checks the signature without seeing your work or private profile.", tag: "04 · CREDENTIAL" },
  ];
  return <><div className="page-heading"><div><h1>Not “Was it AI?”<br/>“Was it you?”</h1><p>A different question. A better way to recognize authentic work.</p></div><button className="button button-primary" onClick={onNew}><Fingerprint size={16}/> Try a demo verification <ArrowRight size={15}/></button></div><div className="how-it-works-grid">{steps.map(step => { const Icon = step.icon; return <article className="how-step card" key={step.tag}><div className="how-step-top"><span className="how-step-icon"><Icon size={30} strokeWidth={1.3}/></span><span className="eyebrow">{step.tag}</span></div><span className="how-step-label">{step.label}</span><h2>{step.title}</h2><p>{step.body}</p></article>; })}</div><section className="secure-box-card"><div className="secure-box-heading"><span className="secure-box-icon"><ShieldCheck size={28}/></span><div><div className="eyebrow">THE SECURE ANALYSIS BOX</div><h3>A small output. A serious privacy boundary.</h3></div><span className="quiet-tag">PRODUCTION DESIGN</span></div><div className="pipeline-strip"><span><FileText size={20}/> Authorized text</span><ChevronRight size={17}/><span><Fingerprint size={20}/> Local signals</span><ChevronRight size={17}/><span><Layers3 size={20}/> Contextual ensemble</span><ChevronRight size={17}/><span><BadgeCheck size={20}/> Probability + flags</span></div><p>Raw text and embeddings never leave the institution in the proposed production topology. Embeddings are still protected data—not anonymous, “irreversible” magic.</p><button className="text-button" onClick={() => onNavigate("blueprint")}>Read the five-part technical blueprint <ArrowRight size={15}/></button></section><div className="lms-note"><Network size={21}/><div><h3>Fits into learning, without taking it over.</h3><p>The design connects Canvas, Blackboard, and Moodle using LTI 1.3 plus platform-specific event adapters. No live LMS connector is installed in this demo.</p></div><div className="lms-chips"><span>Canvas</span><span>Blackboard</span><span>Moodle</span></div></div></>;
}

export function SettingsView({ data, onNavigate, onUpdate, onRefresh, onToast }: PageProps & { onUpdate: (changes: { consent?: boolean; sources?: string[] }) => Promise<void>; onRefresh: () => Promise<void>; onToast: (message: string) => void }) {
  const [pending, setPending] = useState<string | null>(null);
  const [confirmReset, setConfirmReset] = useState(false);
  const [error, setError] = useState("");
  async function update(key: string, changes: { consent?: boolean; sources?: string[] }) { setPending(key); setError(""); try { await onUpdate(changes); onToast("Your preferences are saved."); } catch (err) { setError(err instanceof Error ? err.message : "Please try again."); } finally { setPending(null); } }
  async function reset() { setPending("reset"); setError(""); try { await api("/api/workspace", "DELETE"); await onRefresh(); setConfirmReset(false); onToast("Your previous workspace and share links were deleted. A fresh demo is ready."); } catch (err) { setError(err instanceof Error ? err.message : "Could not reset."); } finally { setPending(null); } }
  return <><div className="page-heading"><div><h1>Your data. Your decision.</h1><p>Stay in control of what contributes to your story.</p></div><span className="settings-trust"><ShieldCheck size={16}/> Privacy is the foundation.</span></div><div className="settings-grid"><div className="settings-main"><section className="card consent-card"><div className="card-heading"><div><h3>Authorship verification</h3><p>A choice you can change at any time.</p></div><span className={`status-badge ${data.consent ? "verified" : "context"}`}>{data.consent ? <Check size={12}/> : <Info size={12}/>} {data.consent ? "Opted in" : "Paused"}</span></div><div className="consent-control"><span className="consent-icon"><Fingerprint size={31} strokeWidth={1.4}/></span><div><h4>Let your authentic work stand out</h4><p>{data.consent ? "New demo verifications and credential minting are enabled." : "New verifications and credential minting are paused."}</p></div><button className={`toggle ${data.consent ? "on" : ""}`} role="switch" aria-checked={data.consent} aria-label="Enable authorship verification" disabled={pending !== null} onClick={() => update("consent", { consent: !data.consent })}><span/></button></div><div className="consent-footnote"><LockKeyhole size={14}/><p>Pausing never changes a regular grade. Existing credential shares stay active until you revoke them under Credentials.</p></div></section>
      <section className="card sources-settings"><div className="card-heading"><div><h3>Your baseline sources</h3><p>Choose which source types may contribute to your profile.</p></div><span className="quiet-tag">DEMO PREFERENCES</span></div>{sourceOptions.map((source, i) => { const Icon = sourceIcons[i]; const enabled = data.sources.includes(source.id); return <div className="source-setting" key={source.id}><span className="source-setting-icon"><Icon size={19}/></span><div><strong>{source.title}{source.id === "email" && <span className="optional-label">Additional authorization</span>}</strong><p>{source.description}</p></div><button className={`toggle ${enabled ? "on" : ""}`} role="switch" aria-checked={enabled} aria-label={`Include ${source.title.toLowerCase()}`} disabled={pending !== null} onClick={() => update(source.id, { sources: enabled ? data.sources.filter(s => s !== source.id) : [...data.sources, source.id] })}><span/></button></div>; })}<p className="source-settings-note"><Info size={13}/> These switches save demo preferences; they do not connect to an LMS or read any email.</p></section>
      <section className="card data-controls"><div className="card-heading"><div><h3>Your records, in your hands</h3><p>Transparency is part of the deal.</p></div><FileText size={20}/></div><div className="data-control-row"><div><strong>Export your demo data</strong><p>Download saved metrics, preferences, and credential references. No raw text is stored.</p></div><button className="button button-secondary" onClick={() => downloadFile(JSON.stringify(data, null, 2), "authwords-my-demo-data.json", "application/json")}><ArrowDownToLine size={15}/> Export</button></div><div className="data-control-row"><div><strong>Reset your demo workspace</strong><p>Delete this session’s records and public share links, then create a fresh synthetic profile.</p></div><button className="button button-danger-outline" disabled={pending !== null} onClick={() => setConfirmReset(true)}><Trash2 size={14}/> Reset</button></div>{confirmReset && <div className="reset-confirmation"><p>This cannot be undone. Previously shared credentials will no longer resolve.</p><button className="button button-secondary" onClick={() => setConfirmReset(false)}>Keep my workspace</button><button className="button button-danger" disabled={pending !== null} onClick={reset}>{pending === "reset" && <LoaderCircle size={14} className="spin"/>} Reset demo</button></div>}</section>{error && <p className="form-error" role="alert">{error}</p>}</div><aside className="settings-aside"><div className="privacy-promise"><ShieldCheck size={35} strokeWidth={1.2}/><h3>Trust isn’t a checkbox.</h3><p>It’s a system designed to keep your writing where it belongs, and put you in control of what leaves.</p><ul><li><Check size={14}/> No raw-text API uploads in this demo</li><li><Check size={14}/> No third-party inference calls</li><li><Check size={14}/> No automated misconduct verdicts</li><li><Check size={14}/> No academic penalty for opting out</li></ul><button className="text-button" onClick={() => onNavigate("blueprint")}>Explore the privacy architecture <ArrowRight size={14}/></button></div><div className="consent-receipt"><span className="eyebrow">YOUR LATEST PREFERENCE UPDATE</span><strong>{formatDate(data.consentUpdatedAt, true)}</strong><p>Saved in your isolated demo workspace. Production consent requires a purpose-specific institutional receipt.</p></div></aside></div></>;
}
