import assert from "node:assert/strict";
import { chromium, request, expect } from "@playwright/test";
import { createLocalJWKSet, jwtVerify } from "jose";

const baseURL = process.env.TEST_BASE_URL || "http://localhost:3000";
const context = await request.newContext({ baseURL });
const other = await request.newContext({ baseURL });
const features = { wordCount: 220, avgSentenceLength: 18.5, lexicalDiversity: .68, punctuationRate: .1, sentenceVariation: .45 };
let browser;
try {
  const response = await context.get("/api/workspace");
  assert.equal(response.status(), 200, "workspace should initialize");
  const initial = await response.json();
  assert.equal(initial.submissions.length, 26);
  assert.equal(initial.credentials.length, 18);
  const repeated = await (await context.get("/api/workspace")).json();
  assert.equal(repeated.submissions[0].id, initial.submissions[0].id, "workspace must persist");
  const isolated = await (await other.get("/api/workspace")).json();
  assert.notEqual(isolated.submissions[0].id, initial.submissions[0].id, "sessions must be isolated");
  const raw = await context.post("/api/submissions", { data: { title: "Rejected raw input", course: "Synthetic course", mode: "essay", features, text: "Raw text must never be accepted" } });
  assert.equal(raw.status(), 400, "strict schema must reject text");
  const origin = await context.post("/api/submissions", { headers: { origin: "https://untrusted.example" }, data: { title: "Foreign origin", course: "Synthetic", mode: "essay", features } });
  assert.equal(origin.status(), 403, "foreign-origin mutation must be rejected");
  await context.patch("/api/workspace", { data: { consent: false } });
  const paused = await context.post("/api/submissions", { data: { title: "Consent test", course: "Synthetic course", mode: "essay", features } });
  assert.equal(paused.status(), 403, "paused consent must block verification");
  await context.patch("/api/workspace", { data: { consent: true, sources: ["timed", "drafts"] } });
  const settings = await (await context.get("/api/workspace")).json();
  assert.deepEqual(settings.sources, ["timed", "drafts"]);
  const createdResponse = await context.post("/api/submissions", { data: { title: "A repeatable synthetic test", course: "Synthetic seminar", mode: "essay", features } });
  assert.equal(createdResponse.status(), 201);
  const { submission } = await createdResponse.json();
  assert.equal(submission.status, "Verified");
  const crossWorkspace = await other.patch(`/api/submissions/${submission.id}`);
  assert.equal(crossWorkspace.status(), 404, "another session cannot access a submission");
  const mintedResponse = await context.post("/api/credentials", { data: { submissionId: submission.id } });
  assert.equal(mintedResponse.status(), 200);
  const minted = await mintedResponse.json();
  const secondMint = await (await context.post("/api/credentials", { data: { submissionId: submission.id } })).json();
  assert.equal(secondMint.id, minted.id, "minting must be idempotent");
  const proof = await (await context.get(`/api/verify/${minted.id}`)).json();
  assert.equal(proof.valid, true);
  assert.ok(!JSON.stringify(proof).includes("Synthetic seminar"), "public proof must not contain private metadata");
  const jwks = await (await context.get("/api/credentials/jwks")).json();
  const { payload } = await jwtVerify(proof.token, createLocalJWKSet(jwks), { algorithms: ["EdDSA"], issuer: "urn:authwords:synthetic-demo", audience: "urn:authwords:public-demo-verifier" });
  assert.equal(payload.demo, true);
  assert.equal(payload.grade, undefined, "credential must not carry a grade claim");
  const parts = proof.token.split(".");
  parts[1] = Buffer.from(JSON.stringify({ ...payload, gradeDisclosed: true, grade: "A+" })).toString("base64url");
  await assert.rejects(jwtVerify(parts.join("."), createLocalJWKSet(jwks)), "tampering must fail signature verification");
  const foreignRevoke = await other.patch("/api/credentials", { data: { id: minted.id, revoked: true } });
  assert.equal(foreignRevoke.status(), 404);
  await context.patch("/api/credentials", { data: { id: minted.id, revoked: true } });
  const revoked = await (await context.get(`/api/verify/${minted.id}`)).json();
  assert.equal(revoked.valid, false);
  assert.equal(revoked.revoked, true);
  const cannotReactivate = await context.post("/api/credentials", { data: { submissionId: submission.id } });
  assert.equal(cannotReactivate.status(), 409);
  const prompt = await context.post("/api/submissions", { data: { title: "Prompt-specific abstention", course: "Synthetic seminar", mode: "prompt", features } });
  const promptResult = (await prompt.json()).submission;
  assert.equal(promptResult.score, null);
  assert.equal(promptResult.status, "Insufficient evidence");
  assert.ok(promptResult.flags.includes("PROMPT_BASELINE_REQUIRED"));
  const review = await context.patch(`/api/submissions/${promptResult.id}`);
  assert.equal((await review.json()).reviewRequested, true);
  console.log("PASS: persistence, isolation, strict data schema, origin checks, consent, signing, tamper resistance, revocation, prompt abstention, review requests.");

  browser = await chromium.launch({ headless: true, args: ["--no-sandbox"], executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined });
  // Set PLAYWRIGHT_IGNORE_HTTPS_ERRORS=1 when a TLS-intercepting proxy sits between this runner and the target.
  const ignoreHTTPSErrors = process.env.PLAYWRIGHT_IGNORE_HTTPS_ERRORS === "1";
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, ignoreHTTPSErrors });
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  // The workspace fetches its data after mount; wait for it before interacting.
  const ready = target => target.locator('main[data-ready="true"]').waitFor({ timeout: 20000 });
  await page.goto(baseURL, { waitUntil: "load" });
  await ready(page);
  await expect(page.getByRole("heading", { name: "Your authorship, at a glance." })).toBeVisible();
  await page.getByRole("link", { name: "My submissions" }).click();
  await page.getByRole("textbox", { name: "Search submissions" }).fill("ethics");
  await expect(page.locator(".submission-table tbody tr")).toHaveCount(7);
  await page.getByRole("textbox", { name: "Search submissions" }).fill("artificial intelligence");
  await expect(page.locator(".submission-table tbody tr")).toHaveCount(1);
  await page.getByRole("button", { name: "The ethics of artificial intelligence", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("link", { name: "System blueprint" }).click();
  await expect(page.getByRole("heading", { name: "Built on trust. By design." })).toBeVisible();
  await page.getByRole("button", { name: "02 Multi-factor engine" }).click();
  await expect(page.getByRole("heading", { name: "Four signals. One contextual judgment." })).toBeVisible();
  await page.getByRole("textbox", { name: "Search blueprint" }).fill("non-reversible");
  await expect(page.getByRole("heading", { name: "The text stays. The evidence travels." })).toBeVisible();
  const downloadEvent = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export blueprint" }).click();
  assert.equal((await downloadEvent).suggestedFilename(), "authwords-production-blueprint.md");
  await page.getByRole("link", { name: "Why not detection?" }).click();
  await expect(page.getByRole("heading", { name: "Detection is a race you cannot win." })).toBeVisible();
  await expect(page.getByText("The customization problem")).toBeVisible();
  await page.getByRole("link", { name: "Flip the assignment" }).click();
  await expect(page.getByRole("heading", { name: "Make the shortcut the lesson." })).toBeVisible();
  await expect(page.locator(".prompt-pane")).toHaveCount(2);
  await page.getByRole("button", { name: "Engineered", exact: true }).click();
  await expect(page.locator(".prompt-pane")).toHaveCount(1);
  await page.goto(`${baseURL}/?view=flip`, { waitUntil: "load" });
  await expect(page.getByRole("heading", { name: "Make the shortcut the lesson." })).toBeVisible();
  await page.getByRole("link", { name: "Overview", exact: true }).click();
  await page.getByRole("button", { name: "Verify new work" }).click();
  await page.getByRole("button", { name: "Use a sample" }).click();
  await page.getByRole("checkbox").check();
  const metricsRequest = page.waitForRequest(req => req.url().endsWith("/api/submissions") && req.method() === "POST");
  await page.getByRole("button", { name: "Run demo verification" }).click();
  const transmitted = (await metricsRequest).postDataJSON();
  assert.ok(!("text" in transmitted), "browser must not transmit raw text");
  assert.ok(!JSON.stringify(transmitted).includes("Learning changes the way"));
  await expect(page.getByRole("heading", { name: "The story behind your submission" })).toBeVisible({ timeout: 10000 });
  await expect(page.getByRole("heading", { name: "A conversation about our shared spaces" })).toBeVisible();
  await page.getByRole("button", { name: "Close dialog" }).click();
  await page.getByRole("link", { name: "Privacy & settings" }).click();
  const consentToggle = page.getByRole("switch", { name: "Enable authorship verification" });
  await consentToggle.click();
  await expect(consentToggle).toHaveAttribute("aria-checked", "false");
  await page.reload({ waitUntil: "load" });
  await ready(page);
  await expect(page.getByRole("switch", { name: "Enable authorship verification" })).toHaveAttribute("aria-checked", "false");
  assert.deepEqual(errors, [], "no browser runtime errors");
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  console.log("PASS: navigation, filtering, accessible dialogs, blueprint search/export, flipped-question views, deep links, browser-only extraction, persisted consent, zero desktop overflow.");

  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, ignoreHTTPSErrors });
  await mobile.goto(baseURL, { waitUntil: "load" });
  await ready(mobile);
  await mobile.getByRole("button", { name: "Open navigation" }).click();
  await mobile.getByRole("link", { name: "Writing profile", exact: true }).click();
  await expect(mobile.getByRole("heading", { name: "A voice that’s uniquely yours." })).toBeVisible();
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
  await mobile.goto(baseURL, { waitUntil: "load" });
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false, "dashboard must not expand the mobile visual viewport");
  await mobile.goto(`${baseURL}/verify/${initial.credentials[0].id}`, { waitUntil: "load" });
  await expect(mobile.getByRole("heading", { name: "Verified authorship", exact: true })).toBeVisible();
  assert.ok(!(await mobile.content()).includes("Grade A"), "public page must not disclose a grade");
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth), false);
  console.log("PASS: mobile navigation, responsive profile, public credential verification.");
  console.log("ALL AUTHWORDS SMOKE TESTS PASSED");
} finally {
  await context.delete("/api/workspace");
  await other.delete("/api/workspace");
  await context.dispose(); await other.dispose();
  if (browser) await browser.close();
}
