import type { Metadata } from "next";
import Link from "next/link";
import { ShieldCheck, ArrowUpRight, Check, Info, LockKeyhole, ExternalLink, CircleX, BadgeCheck } from "lucide-react";
import { verifyDemoCredential } from "@/lib/credentials";
import { Brand, CredentialMedallion } from "@/components/visuals";
import { DemoNotice } from "@/components/primitives";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Verify a credential — AuthWords", robots: { index: false, follow: false }, referrer: "no-referrer" };
export default async function PublicVerification({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const credential = await verifyDemoCredential(id);
  const valid = credential?.valid === true;
  const date = (value: string | undefined) => value ? new Date(value).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" }) : "Not available";
  return <div className="public-page"><header className="public-header"><Link href="/" aria-label="AuthWords home"><Brand/></Link><Link href="/?view=blueprint">The trust behind the proof <ArrowUpRight size={14}/></Link></header><main id="main-content" className="public-content"><div className="public-eyebrow"><ShieldCheck size={14}/> INDEPENDENT CREDENTIAL VERIFICATION</div><h1>Authenticity you can check.</h1><p>A signed claim. A transparent status. No private academic records.</p><article className="public-credential">
    {credential ? <><div className="public-credential-top"><span className="public-demo-tag">SYNTHETIC DEMO · NOT AN ACADEMIC QUALIFICATION</span>{valid ? <CredentialMedallion/> : <CircleX className="public-invalid-icon" size={76} strokeWidth={1}/>}<h2>{valid ? "Verified authorship · Grade A" : credential.revoked ? "This credential is revoked." : "This proof is not valid."}</h2><span className={`public-status ${valid ? "" : "invalid"}`}>{valid ? <BadgeCheck size={14}/> : <Info size={14}/>} {valid ? "Signature valid · Credential active" : credential.revoked ? "Revoked by the workspace owner" : "Expired or unable to verify"}</span></div><div className="public-credential-body"><dl className="public-details"><div><dt>Issuer</dt><dd>AuthWords synthetic demo</dd></div><div><dt>Signature algorithm</dt><dd>Ed25519 · EdDSA</dd></div><div><dt>Issued</dt><dd>{date("issuedAt" in credential ? credential.issuedAt : undefined)}</dd></div><div><dt>Expires</dt><dd>{date("expiresAt" in credential ? credential.expiresAt : undefined)}</dd></div><div><dt>Student identity</dt><dd>Not disclosed or certified</dd></div><div><dt>School / assignment details</dt><dd>Not disclosed</dd></div><div><dt>Credential ID</dt><dd className="public-id">{id}</dd></div></dl><DemoNotice>This cryptographic signature attests only to a synthetic demo result. The grade is illustrative. It does not establish authorship, an actual qualification, or the identity of the person sharing this link.</DemoNotice><div className="public-key-links"><a href="/api/credentials/jwks" target="_blank" rel="noopener noreferrer">Public verification keys <ExternalLink size={12}/></a><a href={`/api/verify/${id}`} target="_blank" rel="noopener noreferrer">Inspect signed proof <ExternalLink size={12}/></a></div></div></> : <div className="public-missing"><CircleX className="public-invalid-icon" size={64} strokeWidth={1}/><h2>We couldn’t find this credential.</h2><p>The link may be incomplete, or its workspace may have been deleted. Ask the person who shared it for a current verification link.</p><Link href="/" className="button button-secondary">Explore AuthWords <ArrowUpRight size={14}/></Link></div>}
  </article><div className="public-privacy-note"><LockKeyhole size={14}/><p>Only the minimal signed claim and its current status are checked. No student profile, writing sample, or school record is returned.</p></div></main><footer className="public-footer">A valid signature proves the issuer’s statement—not the holder’s identity.<br/>AuthWords · Built on trust. By design.</footer></div>;
}
